; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt -passes=argpromotion -verify-each -S < %s | FileCheck %s

target triple = "x86_64-unknown-linux-gnu"

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)
declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1 immarg)
declare void @llvm.memcpy.element.unordered.atomic.p0.p0.i64(ptr, ptr, i64, i32 immarg)
declare void @clobber(ptr)

; Returning the copied value exposes a load to the existing input promotion.
; No caller loop or ownership type is required, and noinline is preserved.
define internal void @copy16(ptr %dst, ptr %src) noinline {
; CHECK-LABEL: define {{[^@]+}}@copy16
; CHECK-SAME: (i128 [[SRC_0_VAL:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    ret i128 [[SRC_0_VAL]]
;
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %dst, ptr align 1 %src, i64 16, i1 false)
  ret void
}

define void @call_copy16(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@call_copy16
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[SRC_VAL:%.*]] = load i128, ptr [[SRC]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = call i128 @copy16(i128 [[SRC_VAL]])
; CHECK-NEXT:    store i128 [[TMP1]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
  call void @copy16(ptr %dst, ptr %src)
  ret void
}

; All source bytes must be loaded before the destination is written, including
; partially overlapping ranges and exact source/destination equality.
define internal void @move16(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@move16
; CHECK-SAME: (i128 [[SRC_0_VAL:%.*]]) {
; CHECK-NEXT:    ret i128 [[SRC_0_VAL]]
;
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 8 %src, i64 16, i1 false)
  ret void
}

define void @call_move16(ptr %p) {
; CHECK-LABEL: define {{[^@]+}}@call_move16
; CHECK-SAME: (ptr [[P:%.*]]) {
; CHECK-NEXT:    [[DST:%.*]] = getelementptr i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[P_VAL:%.*]] = load i128, ptr [[P]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = call i128 @move16(i128 [[P_VAL]])
; CHECK-NEXT:    store i128 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    [[P_VAL1:%.*]] = load i128, ptr [[P]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = call i128 @move16(i128 [[P_VAL1]])
; CHECK-NEXT:    store i128 [[TMP2]], ptr [[P]], align 1
; CHECK-NEXT:    ret void
;
  %dst = getelementptr i8, ptr %p, i64 1
  call void @move16(ptr %dst, ptr %p)
  call void @move16(ptr %p, ptr %p)
  ret void
}

define internal void @copy3(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy3
; CHECK-SAME: (i24 [[SRC_0_VAL:%.*]]) {
; CHECK-NEXT:    ret i24 [[SRC_0_VAL]]
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
  ret void
}

define void @call_copy3(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@call_copy3
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[SRC_VAL:%.*]] = load i24, ptr [[SRC]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = call i24 @copy3(i24 [[SRC_VAL]])
; CHECK-NEXT:    store i24 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    ret void
;
  call void @copy3(ptr %dst, ptr %src)
  ret void
}

; Input promotion must not move the load ahead of a source modification.
define internal void @copy_after_clobber(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_after_clobber
; CHECK-SAME: (ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @clobber(ptr [[SRC]])
; CHECK-NEXT:    [[TMP1:%.*]] = load i128, ptr [[SRC]], align 1
; CHECK-NEXT:    ret i128 [[TMP1]]
;
  call void @clobber(ptr %src)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @call_copy_after_clobber(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@call_copy_after_clobber
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i128 @copy_after_clobber(ptr [[SRC]])
; CHECK-NEXT:    store i128 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    ret void
;
  call void @copy_after_clobber(ptr %dst, ptr %src)
  ret void
}

define internal void @copy_after_store(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_after_store
; CHECK-SAME: (ptr [[SRC:%.*]]) {
; CHECK-NEXT:    store i8 42, ptr [[SRC]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i128, ptr [[SRC]], align 1
; CHECK-NEXT:    ret i128 [[TMP1]]
;
  store i8 42, ptr %src
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @call_copy_after_store(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@call_copy_after_store
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i128 @copy_after_store(ptr [[SRC]])
; CHECK-NEXT:    store i128 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    ret void
;
  call void @copy_after_store(ptr %dst, ptr %src)
  ret void
}

define internal void @copy_offset(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_offset
; CHECK-SAME: (i128 [[SRC_4_VAL:%.*]]) {
; CHECK-NEXT:    ret i128 [[SRC_4_VAL]]
;
  %p = getelementptr i8, ptr %src, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 2 %dst, ptr align 4 %p, i64 16, i1 false)
  ret void
}

define void @call_copy_offset(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@call_copy_offset
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[SRC]], i64 4
; CHECK-NEXT:    [[SRC_VAL:%.*]] = load i128, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = call i128 @copy_offset(i128 [[SRC_VAL]])
; CHECK-NEXT:    store i128 [[TMP2]], ptr [[DST]], align 2
; CHECK-NEXT:    ret void
;
  call void @copy_offset(ptr %dst, ptr %src)
  ret void
}

define internal void @copy_zero(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_zero
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[SRC]], i64 0, i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
  ret void
}

define internal void @copy_dynamic(ptr %dst, ptr %src, i64 %n) {
; CHECK-LABEL: define {{[^@]+}}@copy_dynamic
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[SRC]], i64 [[N]], i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
  ret void
}

define internal void @copy_large(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_large
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[SRC]], i64 32, i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
  ret void
}

define internal void @copy_volatile(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_volatile
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[SRC]], i64 16, i1 true)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
  ret void
}

define internal void @copy_atomic(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy_atomic
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.element.unordered.atomic.p0.p0.i64(ptr align 4 [[DST]], ptr align 4 [[SRC]], i64 16, i32 4)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.element.unordered.atomic.p0.p0.i64(ptr align 4 %dst, ptr align 4 %src, i64 16, i32 4)
  ret void
}

define void @negative_calls(ptr %dst, ptr %src, i64 %n) {
; CHECK-LABEL: define {{[^@]+}}@negative_calls
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    call void @copy_zero(ptr [[DST]], ptr [[SRC]])
; CHECK-NEXT:    call void @copy_dynamic(ptr [[DST]], ptr [[SRC]], i64 [[N]])
; CHECK-NEXT:    call void @copy_large(ptr [[DST]], ptr [[SRC]])
; CHECK-NEXT:    call void @copy_volatile(ptr [[DST]], ptr [[SRC]])
; CHECK-NEXT:    call void @copy_atomic(ptr [[DST]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  call void @copy_zero(ptr %dst, ptr %src)
  call void @copy_dynamic(ptr %dst, ptr %src, i64 %n)
  call void @copy_large(ptr %dst, ptr %src)
  call void @copy_volatile(ptr %dst, ptr %src)
  call void @copy_atomic(ptr %dst, ptr %src)
  ret void
}
