; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt < %s -mtriple=x86_64-- -mcpu=znver5 -passes="print<cost-model>" -cost-kind=all -disable-output 2>&1 | FileCheck %s --check-prefix=ZEN
; RUN: opt < %s -mtriple=x86_64-- -mcpu=core2 -passes="print<cost-model>" -cost-kind=all -disable-output 2>&1 | FileCheck %s --check-prefix=SSE
; RUN: opt < %s -mtriple=x86_64-- -mcpu=sandybridge -passes="print<cost-model>" -cost-kind=all -disable-output 2>&1 | FileCheck %s --check-prefix=AVX1
; RUN: opt < %s -mtriple=x86_64-apple-darwin -mcpu=core2 -passes="print<cost-model>" -cost-kind=all -disable-output 2>&1 | FileCheck %s --check-prefix=DARWIN
; RUN: opt < %s -mtriple=i386-- -mcpu=core2 -passes="print<cost-model>" -cost-kind=all -disable-output 2>&1 | FileCheck %s --check-prefix=X86

; Estimate the existing bounded load/store expansion, including overlapping
; tails. Latency is the sum of instruction costs, not a critical-path model.

@constant = private constant [16 x i8] zeroinitializer

define void @sizes(ptr %dst, ptr %src) {
; ZEN-LABEL: 'sizes'
; ZEN-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 8, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:9 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:15 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:18 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:9 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:18 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 128, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:24 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 129, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:36 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 256, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:10 CodeSize:10 Lat:42 SizeLat:10 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 257, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1024, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; SSE-LABEL: 'sizes'
; SSE-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 8, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:18 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 128, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 129, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 256, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 257, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1024, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; AVX1-LABEL: 'sizes'
; AVX1-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 8, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:7 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:13 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 128, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 129, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 256, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 257, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1024, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; DARWIN-LABEL: 'sizes'
; DARWIN-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 8, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:18 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 128, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 129, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 256, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 257, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1024, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; X86-LABEL: 'sizes'
; X86-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:6 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:7 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 8, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:21 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:28 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:28 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 128, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 129, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 256, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 257, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1024, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 3, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 8, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 128, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 129, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 256, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 257, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 1024, i1 false)
  ret void
}

define void @scalar(ptr %dst, ptr %src) noimplicitfloat {
; ZEN-LABEL: 'scalar'
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:18 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:16 CodeSize:16 Lat:48 SizeLat:16 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 65, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; SSE-LABEL: 'scalar'
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:18 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:16 CodeSize:16 Lat:48 SizeLat:16 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 65, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; AVX1-LABEL: 'scalar'
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:18 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:16 CodeSize:16 Lat:48 SizeLat:16 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 65, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; DARWIN-LABEL: 'scalar'
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:6 CodeSize:6 Lat:18 SizeLat:6 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:16 CodeSize:16 Lat:48 SizeLat:16 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 65, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; X86-LABEL: 'scalar'
; X86-NEXT:  Cost Model: Found costs of RThru:8 CodeSize:8 Lat:24 SizeLat:8 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:12 CodeSize:12 Lat:36 SizeLat:12 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:16 CodeSize:16 Lat:48 SizeLat:16 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 65, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 31, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 65, i1 false)
  ret void
}

define void @alignments(ptr %dst, ptr %src) {
; ZEN-LABEL: 'alignments'
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:9 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:9 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:15 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 24, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:18 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 31, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:9 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 32, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; SSE-LABEL: 'alignments'
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:13 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 24, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 31, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 32, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; AVX1-LABEL: 'alignments'
; AVX1-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:7 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:2 CodeSize:2 Lat:7 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:13 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 24, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 31, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:2 Lat:8 SizeLat:2 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 32, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; DARWIN-LABEL: 'alignments'
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:12 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:13 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 24, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 31, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 32, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; X86-LABEL: 'alignments'
; X86-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 24, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 31, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:14 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 32, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 31, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 32 %dst, ptr align 32 %src, i64 32, i1 false)
  ret void
}

define void @optsize(ptr %dst, ptr %src) optsize {
; ZEN-LABEL: 'optsize'
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:18 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; SSE-LABEL: 'optsize'
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; AVX1-LABEL: 'optsize'
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; DARWIN-LABEL: 'optsize'
; DARWIN-NEXT:  Cost Model: Found costs of RThru:16 CodeSize:16 Lat:56 SizeLat:16 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; X86-LABEL: 'optsize'
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
  ret void
}

define void @minsize(ptr %dst, ptr %src) minsize optsize {
; ZEN-LABEL: 'minsize'
; ZEN-NEXT:  Cost Model: Found costs of RThru:4 CodeSize:4 Lat:18 SizeLat:4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; SSE-LABEL: 'minsize'
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; AVX1-LABEL: 'minsize'
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; DARWIN-LABEL: 'minsize'
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; X86-LABEL: 'minsize'
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 16 %src, i64 128, i1 false)
  ret void
}

define void @fallbacks(ptr %dst, ptr %src, i64 %n) {
; ZEN-LABEL: 'fallbacks'
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
; ZEN-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 true)
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr @constant, i64 16, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 -1, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i128(ptr %dst, ptr %src, i128 18446744073709551616, i1 false)
; ZEN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; SSE-LABEL: 'fallbacks'
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
; SSE-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 true)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr @constant, i64 16, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 -1, i1 false)
; SSE-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i128(ptr %dst, ptr %src, i128 18446744073709551616, i1 false)
; SSE-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; AVX1-LABEL: 'fallbacks'
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
; AVX1-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 true)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr @constant, i64 16, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 -1, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i128(ptr %dst, ptr %src, i128 18446744073709551616, i1 false)
; AVX1-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; DARWIN-LABEL: 'fallbacks'
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
; DARWIN-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 true)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr @constant, i64 16, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 -1, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i128(ptr %dst, ptr %src, i128 18446744073709551616, i1 false)
; DARWIN-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
; X86-LABEL: 'fallbacks'
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
; X86-NEXT:  Cost Model: Found costs of 0 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 true)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr @constant, i64 16, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 -1, i1 false)
; X86-NEXT:  Cost Model: Found costs of 4 for: call void @llvm.memcpy.p0.p0.i128(ptr %dst, ptr %src, i128 18446744073709551616, i1 false)
; X86-NEXT:  Cost Model: Found costs of RThru:0 CodeSize:1 Lat:1 SizeLat:1 for: ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 true)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 0, i1 true)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr @constant, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 -1, i1 false)
  call void @llvm.memcpy.p0.p0.i128(ptr %dst, ptr %src, i128 18446744073709551616, i1 false)
  ret void
}

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare void @llvm.memcpy.p0.p0.i128(ptr, ptr, i128, i1)
