; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt < %s -mtriple=x86_64-- -mcpu=znver5 -passes="print<cost-model>" -cost-kind=latency -disable-output 2>&1 | FileCheck %s --check-prefix=ZEN
; RUN: opt < %s -mtriple=x86_64-- -mcpu=haswell -passes="print<cost-model>" -cost-kind=latency -disable-output 2>&1 | FileCheck %s --check-prefix=HSW
; RUN: opt < %s -mtriple=i386-- -mcpu=i386 -passes="print<cost-model>" -cost-kind=latency -disable-output 2>&1 | FileCheck %s --check-prefix=FALLBACK
; RUN: opt < %s -passes="print<cost-model>" -cost-kind=latency -disable-output 2>&1 | FileCheck %s --check-prefix=FALLBACK

; Scheduling costs apply only to simple, legal full-register memory operations.
; These are instruction latencies, not store-to-load forwarding latencies.
define void @loads(ptr %p) {
; ZEN-LABEL: 'loads'
; ZEN-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i8 = load i8, ptr %p, align 1
; ZEN-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i16 = load i16, ptr %p, align 2
; ZEN-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i32 = load i32, ptr %p, align 4
; ZEN-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i64 = load i64, ptr %p, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %f32 = load float, ptr %p, align 4
; ZEN-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %f64 = load double, ptr %p, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v128 = load <2 x i64>, ptr %p, align 16
; ZEN-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v128u = load <2 x i64>, ptr %p, align 1
; ZEN-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v256 = load <4 x i64>, ptr %p, align 32
; ZEN-NEXT:  Cost Model: Found an estimated cost of 8 for instruction: %v512 = load <8 x i64>, ptr %p, align 64
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; HSW-LABEL: 'loads'
; HSW-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i8 = load i8, ptr %p, align 1
; HSW-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i16 = load i16, ptr %p, align 2
; HSW-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i32 = load i32, ptr %p, align 4
; HSW-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %i64 = load i64, ptr %p, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %f32 = load float, ptr %p, align 4
; HSW-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %f64 = load double, ptr %p, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v128 = load <2 x i64>, ptr %p, align 16
; HSW-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %v128u = load <2 x i64>, ptr %p, align 1
; HSW-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %v256 = load <4 x i64>, ptr %p, align 32
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %v512 = load <8 x i64>, ptr %p, align 64
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; FALLBACK-LABEL: 'loads'
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %i8 = load i8, ptr %p, align 1
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %i16 = load i16, ptr %p, align 2
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %i32 = load i32, ptr %p, align 4
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %i64 = load i64, ptr %p, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %f32 = load float, ptr %p, align 4
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %f64 = load double, ptr %p, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %v128 = load <2 x i64>, ptr %p, align 16
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %v128u = load <2 x i64>, ptr %p, align 1
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %v256 = load <4 x i64>, ptr %p, align 32
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %v512 = load <8 x i64>, ptr %p, align 64
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  %i8 = load i8, ptr %p, align 1
  %i16 = load i16, ptr %p, align 2
  %i32 = load i32, ptr %p, align 4
  %i64 = load i64, ptr %p, align 8
  %f32 = load float, ptr %p, align 4
  %f64 = load double, ptr %p, align 8
  %v128 = load <2 x i64>, ptr %p, align 16
  %v128u = load <2 x i64>, ptr %p, align 1
  %v256 = load <4 x i64>, ptr %p, align 32
  %v512 = load <8 x i64>, ptr %p, align 64
  ret void
}

define void @fallbacks(ptr %p) {
; ZEN-LABEL: 'fallbacks'
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %odd = load i24, ptr %p, align 1
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %wide = load i128, ptr %p, align 16
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %smallvec = load <2 x i32>, ptr %p, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %predicate = load <16 x i1>, ptr %p, align 2
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %aggregate = load { i32, i64 }, ptr %p, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %atomic = load atomic i64, ptr %p monotonic, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %volatile = load volatile i64, ptr %p, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; HSW-LABEL: 'fallbacks'
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %odd = load i24, ptr %p, align 1
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %wide = load i128, ptr %p, align 16
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %smallvec = load <2 x i32>, ptr %p, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %predicate = load <16 x i1>, ptr %p, align 2
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %aggregate = load { i32, i64 }, ptr %p, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %atomic = load atomic i64, ptr %p monotonic, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %volatile = load volatile i64, ptr %p, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; FALLBACK-LABEL: 'fallbacks'
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %odd = load i24, ptr %p, align 1
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %wide = load i128, ptr %p, align 16
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %smallvec = load <2 x i32>, ptr %p, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %predicate = load <16 x i1>, ptr %p, align 2
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %aggregate = load { i32, i64 }, ptr %p, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %atomic = load atomic i64, ptr %p monotonic, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %volatile = load volatile i64, ptr %p, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  %odd = load i24, ptr %p, align 1
  %wide = load i128, ptr %p, align 16
  %smallvec = load <2 x i32>, ptr %p, align 8
  %predicate = load <16 x i1>, ptr %p, align 2
  %aggregate = load { i32, i64 }, ptr %p, align 8
  %atomic = load atomic i64, ptr %p monotonic, align 8
  %volatile = load volatile i64, ptr %p, align 8
  ret void
}

define void @stores(ptr %p, i64 %x, <2 x i64> %v) {
; ZEN-LABEL: 'stores'
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store i64 %x, ptr %p, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i64> %v, ptr %p, align 16
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i64> %v, ptr %p, align 1
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store atomic i64 %x, ptr %p seq_cst, align 8
; ZEN-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; HSW-LABEL: 'stores'
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store i64 %x, ptr %p, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i64> %v, ptr %p, align 16
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i64> %v, ptr %p, align 1
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store atomic i64 %x, ptr %p seq_cst, align 8
; HSW-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; FALLBACK-LABEL: 'stores'
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store i64 %x, ptr %p, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i64> %v, ptr %p, align 16
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i64> %v, ptr %p, align 1
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store atomic i64 %x, ptr %p seq_cst, align 8
; FALLBACK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  store i64 %x, ptr %p, align 8
  store <2 x i64> %v, ptr %p, align 16
  store <2 x i64> %v, ptr %p, align 1
  store atomic i64 %x, ptr %p seq_cst, align 8
  ret void
}
