; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -aa-pipeline=basic-aa -passes=gvn -S < %s | FileCheck %s

define i64 @source_prefix(ptr %dst, ptr %src) {
; CHECK-LABEL: @source_prefix(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 16, i1 false)
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[BEFORE]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i1 false)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @source_inline(ptr %dst, ptr %src) {
; CHECK-LABEL: @source_inline(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.inline.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 16, i1 false)
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[BEFORE]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.inline.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i1 false)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @larger_than_source(ptr %dst, ptr %src) {
; CHECK-LABEL: @larger_than_source(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[DST:%.*]], ptr align 4 [[SRC]], i64 4, i1 false)
; CHECK-NEXT:    [[AFTER:%.*]] = load i64, ptr [[SRC]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[AFTER]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %dst, ptr align 4 %src, i64 4, i1 false)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @unknown_length(ptr %dst, ptr %src, i64 %n) {
; CHECK-LABEL: @unknown_length(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 [[N:%.*]], i1 false)
; CHECK-NEXT:    [[AFTER:%.*]] = load i64, ptr [[SRC]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[AFTER]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 %n, i1 false)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @overlap_allowed(ptr %dst, ptr %src) {
; CHECK-LABEL: @overlap_allowed(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 16, i1 false)
; CHECK-NEXT:    [[AFTER:%.*]] = load i64, ptr [[SRC]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[AFTER]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i1 false)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @volatile_copy(ptr %dst, ptr %src) {
; CHECK-LABEL: @volatile_copy(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 16, i1 true)
; CHECK-NEXT:    [[AFTER:%.*]] = load i64, ptr [[SRC]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[AFTER]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i1 true)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @bundled_copy(ptr %dst, ptr %src) {
; CHECK-LABEL: @bundled_copy(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 16, i1 false) [ "unknown"(ptr [[SRC]]) ]
; CHECK-NEXT:    [[AFTER:%.*]] = load i64, ptr [[SRC]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[AFTER]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i1 false) [ "unknown"(ptr %src) ]
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

define i64 @atomic_copy(ptr %dst, ptr %src) {
; CHECK-LABEL: @atomic_copy(
; CHECK-NEXT:    [[BEFORE:%.*]] = load i64, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.element.unordered.atomic.p0.p0.i64(ptr align 8 [[DST:%.*]], ptr align 8 [[SRC]], i64 16, i32 8)
; CHECK-NEXT:    [[AFTER:%.*]] = load i64, ptr [[SRC]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[BEFORE]], [[AFTER]]
; CHECK-NEXT:    ret i64 [[SUM]]
;
  %before = load i64, ptr %src, align 8
  call void @llvm.memcpy.element.unordered.atomic.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i32 8)
  %after = load i64, ptr %src, align 8
  %sum = add i64 %before, %after
  ret i64 %sum
}

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)
declare void @llvm.memcpy.inline.p0.p0.i64(ptr, ptr, i64 immarg, i1 immarg)
declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1 immarg)
declare void @llvm.memcpy.element.unordered.atomic.p0.p0.i64(ptr, ptr, i64, i32 immarg)
