#!/usr/bin/env python3
# ===----------------------------------------------------------------------===##
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ===----------------------------------------------------------------------===##

"""run.py is a utility for running a program.

It can perform code signing, forward arguments to the program, and return the
program's error code.
"""

import argparse
import contextlib
import os
import platform
import subprocess
import tempfile


@contextlib.contextmanager
def shortWorkingDirectory(execdir):
    """Yields a name for execdir that CreateProcessW accepts as a working directory.

    CreateProcessW rejects a current directory longer than MAX_PATH even when
    the caller and the system have opted into long paths, and a child that is
    not itself long-path aware could not resolve relative names against such a
    directory anyway. When the execution directory is that deep, give it a
    second, short name: a junction in the temp directory, removed afterwards.
    Everything the test writes relative to its working directory lands in the
    real directory.
    """
    # Leave room for the names a test creates relative to its working
    # directory, which the child resolves against the same limit.
    if platform.system() != "Windows" or len(execdir) + 40 < 260:
        yield execdir
        return
    try:
        import _winapi
        createJunction = _winapi.CreateJunction
    except (ImportError, AttributeError):
        yield execdir
        return
    parent = tempfile.mkdtemp(prefix="lit-")
    link = os.path.join(parent, "d")
    createJunction(execdir, link)
    try:
        yield link
    finally:
        os.rmdir(link)
        os.rmdir(parent)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--execdir", type=str, required=True)
    parser.add_argument("--codesign_identity", type=str, required=False, default=None)
    parser.add_argument("--env", type=str, nargs="*", required=False, default=[])
    parser.add_argument(
        "--prepend_env", type=str, nargs="*", required=False, default=[]
    )
    parser.add_argument("command", nargs=argparse.ONE_OR_MORE)
    args = parser.parse_args()
    commandLine = args.command

    # HACK:
    # If an argument is a file that ends in `.tmp.exe`, assume it is the name
    # of an executable generated by a test file. We call these test-executables
    # below. This allows us to do custom processing like codesigning test-executables.
    # It's also possible for there to be no such executable, for example in the case
    # of a .sh.cpp test.
    isTestExe = lambda exe: exe.endswith(".tmp.exe") and os.path.exists(exe)

    # Do any necessary codesigning of test-executables found in the command line.
    if args.codesign_identity:
        for exe in filter(isTestExe, commandLine):
            codesign = ["codesign", "-f", "-s", args.codesign_identity, exe]
            subprocess.check_call(codesign, env={})

    # Extract environment variables into a dictionary
    env = {k: v for (k, v) in map(lambda s: s.split("=", 1), args.env)}

    # Set environment variables where we prepend the given value to the
    # existing environment variable.
    for (k, v) in map(lambda s: s.split("=", 1), args.prepend_env):
        if k in os.environ:
            v = v + os.pathsep + os.environ[k]
        env[k] = v

    executable = None
    if platform.system() == "Windows":
        # Pass some extra variables through on Windows:
        # COMSPEC is needed for running subprocesses via std::system().
        if "COMSPEC" in os.environ:
            env["COMSPEC"] = os.environ.get("COMSPEC")
        # TEMP is needed for placing temp files in a sensible directory.
        if "TEMP" in os.environ:
            env["TEMP"] = os.environ.get("TEMP")
        # CreateProcessW limits the program name parsed out of the command
        # line to MAX_PATH even when long paths are enabled, whereas the
        # program passed as lpApplicationName has no such limit. Test
        # executables live in deep per-test directories, so name the program
        # separately when it is given as a full path to an existing file
        # (lpApplicationName gets neither a PATH search nor a default
        # extension, so anything else keeps the command-line lookup).
        program = commandLine[0]
        if os.path.isabs(program) and os.path.isfile(program):
            executable = program

    # Run the command line with the given environment in the execution directory.
    with shortWorkingDirectory(args.execdir) as cwd:
        return subprocess.call(
            commandLine, executable=executable, cwd=cwd, env=env, shell=False
        )


if __name__ == "__main__":
    exit(main())
