; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64-linux-gnu -verify-machineinstrs | FileCheck %s --check-prefix=LE
; RUN: llc < %s -mtriple=aarch64_be-linux-gnu -verify-machineinstrs | FileCheck %s --check-prefix=BE
; Partial-store forwarding requires target profitability approval.

define void @low_half(ptr %src, ptr %dst, i64 %x) {
; LE-LABEL: low_half:
; LE:       // %bb.0:
; LE-NEXT:    str x2, [x0]
; LE-NEXT:    ldr q0, [x0]
; LE-NEXT:    str q0, [x1]
; LE-NEXT:    ret
;
; BE-LABEL: low_half:
; BE:       // %bb.0:
; BE-NEXT:    str x2, [x0]
; BE-NEXT:    ld1 { v0.2d }, [x0]
; BE-NEXT:    st1 { v0.2d }, [x1]
; BE-NEXT:    ret
  store i64 %x, ptr %src, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret void
}
define void @high_half(ptr %src, ptr %dst, i64 %x) {
; LE-LABEL: high_half:
; LE:       // %bb.0:
; LE-NEXT:    str x2, [x0, #8]
; LE-NEXT:    ldr q0, [x0]
; LE-NEXT:    str q0, [x1]
; LE-NEXT:    ret
;
; BE-LABEL: high_half:
; BE:       // %bb.0:
; BE-NEXT:    str x2, [x0, #8]
; BE-NEXT:    ld1 { v0.2d }, [x0]
; BE-NEXT:    st1 { v0.2d }, [x1]
; BE-NEXT:    ret
  %field = getelementptr i8, ptr %src, i64 8
  store i64 %x, ptr %field, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret void
}
