//===-- crt_pseudo_reloc_windows.cpp - COFF pseudo-relocation runtime -----===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Runtime support for COFF pseudo-relocations generated by LLD's -auto-import.
// Patches data references to auto-imported DLL symbols after IAT resolution.
//
// Required for Itanium vtables in COFF - PE cannot store DLL runtime addresses
// directly, so LLD generates a pseudo-reloc table and this code patches the
// addresses at module load time.
//
//===----------------------------------------------------------------------===//

#if defined(_WIN32_ITANIUM) || defined(__NTPOSIX__)

#include <stddef.h>
#include <stdint.h>

//===----------------------------------------------------------------------===//
// Windows API imports (no windows.h dependency)
//===----------------------------------------------------------------------===//

extern "C" {
void *__attribute__((dllimport)) __stdcall RtlAllocateHeap(void *,
                                                           unsigned long,
                                                           size_t);
int __attribute__((dllimport)) __stdcall RtlFreeHeap(void *, unsigned long,
                                                     void *);
void *__attribute__((dllimport)) __stdcall RtlImageNtHeader(void *);
void *__attribute__((dllimport)) __stdcall RtlPcToFileHeader(void *, void **);
long __attribute__((dllimport)) __stdcall NtFlushInstructionCache(void *,
                                                                  void *,
                                                                  size_t);
long __attribute__((dllimport)) __stdcall NtQueryVirtualMemory(
    void *, const void *, unsigned long, void *, size_t, size_t *);
long __attribute__((dllimport)) __stdcall NtProtectVirtualMemory(
    void *, void **, size_t *, unsigned long, unsigned long *);
}

//===----------------------------------------------------------------------===//
// Architecture detection
//===----------------------------------------------------------------------===//

#if defined(_M_IX86) || defined(__i386__)
#define CRT_PSEUDO_RELOC_SYM_PREFIX "_"
#else
#define CRT_PSEUDO_RELOC_SYM_PREFIX ""
#endif

//===----------------------------------------------------------------------===//
// Constants
//===----------------------------------------------------------------------===//

namespace {

using NTSTATUS = long;

constexpr unsigned long kPageReadwrite = 0x04;
constexpr unsigned long kPageExecute = 0x10;
constexpr unsigned long kPageExecuteRead = 0x20;
constexpr unsigned long kPageExecuteReadwrite = 0x40;
constexpr unsigned long kMemCommit = 0x1000;
constexpr unsigned long kMemoryBasicInformation = 0;
constexpr size_t kPageSize = 4096;
constexpr size_t kPageMask = ~(kPageSize - 1);

inline bool ntSuccess(NTSTATUS status) { return status >= 0; }

inline void *ntCurrentProcess() {
  return reinterpret_cast<void *>(static_cast<intptr_t>(-1));
}

struct ProcessEnvironmentBlock {
#if defined(_WIN64)
  unsigned char Reserved[0x30];
#else
  unsigned char Reserved[0x18];
#endif
  void *ProcessHeap;
};

inline ProcessEnvironmentBlock *ntCurrentPeb() {
  ProcessEnvironmentBlock *peb;
#if defined(__x86_64__) || defined(_M_X64)
  __asm__ __volatile__("movq %%gs:0x60, %0" : "=r"(peb));
#elif defined(__i386__) || defined(_M_IX86)
  __asm__ __volatile__("movl %%fs:0x30, %0" : "=r"(peb));
#elif defined(__aarch64__) || defined(_M_ARM64)
  __asm__ __volatile__("ldr %0, [x18, #0x60]" : "=r"(peb));
#else
#error "Unsupported architecture for Windows pseudo-relocation runtime"
#endif
  return peb;
}

inline void *ntProcessHeap() { return ntCurrentPeb()->ProcessHeap; }

} // namespace

//===----------------------------------------------------------------------===//
// PE structures (minimal)
//===----------------------------------------------------------------------===//

namespace {

struct MemoryBasicInformation {
  void *BaseAddress;
  void *AllocationBase;
  unsigned long AllocationProtect;
  size_t RegionSize;
  unsigned long State;
  unsigned long Protect;
  unsigned long Type;
};

struct ImageFileHeader {
  unsigned short Machine, NumberOfSections;
  unsigned long TimeDateStamp, PointerToSymbolTable, NumberOfSymbols;
  unsigned short SizeOfOptionalHeader, Characteristics;
};

#if defined(_M_X64) || defined(__x86_64__) || defined(_M_ARM64) ||             \
    defined(__aarch64__)
struct ImageOptionalHeader {
  unsigned short Magic;
  unsigned char MajorLinkerVersion, MinorLinkerVersion;
  unsigned long SizeOfCode, SizeOfInitializedData, SizeOfUninitializedData;
  unsigned long AddressOfEntryPoint, BaseOfCode;
  uint64_t ImageBase;
  unsigned long SectionAlignment, FileAlignment;
  unsigned short MajorOperatingSystemVersion, MinorOperatingSystemVersion;
  unsigned short MajorImageVersion, MinorImageVersion;
  unsigned short MajorSubsystemVersion, MinorSubsystemVersion;
  unsigned long Win32VersionValue, SizeOfImage;
};
#else
struct ImageOptionalHeader {
  unsigned short Magic;
  unsigned char MajorLinkerVersion, MinorLinkerVersion;
  unsigned long SizeOfCode, SizeOfInitializedData, SizeOfUninitializedData;
  unsigned long AddressOfEntryPoint, BaseOfCode, BaseOfData, ImageBase;
  unsigned long SectionAlignment, FileAlignment;
  unsigned short MajorOperatingSystemVersion, MinorOperatingSystemVersion;
  unsigned short MajorImageVersion, MinorImageVersion;
  unsigned short MajorSubsystemVersion, MinorSubsystemVersion;
  unsigned long Win32VersionValue, SizeOfImage;
};
#endif

struct ImageNtHeaders {
  unsigned long Signature;
  ImageFileHeader FileHeader;
  ImageOptionalHeader OptionalHeader;
};

// LLD pseudo-relocation structures.
struct PseudoRelocV1 {
  unsigned long addend;
  unsigned long target;
};

struct PseudoRelocV2 {
  unsigned long sym;
  unsigned long target;
  unsigned long flags;
};

struct PseudoRelocHeader {
  unsigned long magic1;
  unsigned long magic2;
  unsigned long version;
};

} // namespace

//===----------------------------------------------------------------------===//
// Page protection tracking
//===----------------------------------------------------------------------===//

namespace {

using uptr = unsigned long long;

struct PageRange {
  uptr startPage;
  uptr endPage;
  unsigned long oldProtect;
  bool wasExecutable;
};

class PageTracker {
  static constexpr int kInlineCapacity = 16;
  PageRange inlineStorage_[kInlineCapacity];
  PageRange *data_ = inlineStorage_;
  int size_ = 0;
  int capacity_ = kInlineCapacity;
  bool usingHeap_ = false;

public:
  PageTracker() = default;
  PageTracker(const PageTracker &) = delete;
  PageTracker &operator=(const PageTracker &) = delete;

  ~PageTracker() {
    restoreAll();
    if (usingHeap_ && data_)
      RtlFreeHeap(ntProcessHeap(), 0, data_);
  }

  bool makeWritable(void *addr, size_t size) {
    uptr startPage = reinterpret_cast<uptr>(addr) & kPageMask;
    uptr endPage =
        (reinterpret_cast<uptr>(addr) + size + kPageSize - 1) & kPageMask;

    for (int i = 0; i < size_; ++i)
      if (startPage >= data_[i].startPage && endPage <= data_[i].endPage)
        return true;

    MemoryBasicInformation mbi;
    bool wasExecutable = false;
    size_t returnLength = 0;
    if (ntSuccess(::NtQueryVirtualMemory(ntCurrentProcess(), addr,
                                         kMemoryBasicInformation, &mbi,
                                         sizeof(mbi), &returnLength)) &&
        returnLength >= sizeof(mbi))
      wasExecutable =
          (mbi.Protect & (kPageExecute | kPageExecuteRead |
                          kPageExecuteReadwrite)) != 0;

    unsigned long oldProtect;
    void *base = reinterpret_cast<void *>(startPage);
    size_t regionSize = endPage - startPage;
    // Use PAGE_EXECUTE_READWRITE for executable pages to avoid DEP violations
    // if the pseudo-reloc code itself shares a page with the target.
    unsigned long newProtect =
        wasExecutable ? kPageExecuteReadwrite : kPageReadwrite;
    if (!ntSuccess(::NtProtectVirtualMemory(ntCurrentProcess(), &base,
                                            &regionSize, newProtect,
                                            &oldProtect)))
      return false;

    if (size_ >= capacity_ && !grow()) {
      unsigned long dummy;
      void *restoreBase = reinterpret_cast<void *>(startPage);
      size_t restoreSize = endPage - startPage;
      ::NtProtectVirtualMemory(ntCurrentProcess(), &restoreBase, &restoreSize,
                               oldProtect, &dummy);
      return false;
    }

    data_[size_++] = {startPage, endPage, oldProtect, wasExecutable};
    return true;
  }

  void restoreAll() {
#if defined(_M_ARM64) || defined(__aarch64__) || defined(_M_ARM) ||            \
    defined(__arm__)
    for (int i = 0; i < size_; ++i)
      if (data_[i].wasExecutable)
        NtFlushInstructionCache(ntCurrentProcess(),
                                reinterpret_cast<void *>(data_[i].startPage),
                                data_[i].endPage - data_[i].startPage);
#endif
    for (int i = 0; i < size_; ++i) {
      unsigned long dummy;
      void *base = reinterpret_cast<void *>(data_[i].startPage);
      size_t regionSize = data_[i].endPage - data_[i].startPage;
      ::NtProtectVirtualMemory(ntCurrentProcess(), &base, &regionSize,
                               data_[i].oldProtect, &dummy);
    }
    size_ = 0;
  }

private:
  bool grow() {
    int newCapacity = capacity_ * 2;
    auto *newData = static_cast<PageRange *>(
        RtlAllocateHeap(ntProcessHeap(), 0, newCapacity * sizeof(PageRange)));
    if (!newData)
      return false;
    __builtin_memcpy(newData, data_, size_ * sizeof(PageRange));
    if (usingHeap_)
      RtlFreeHeap(ntProcessHeap(), 0, data_);
    data_ = newData;
    capacity_ = newCapacity;
    usingHeap_ = true;
    return true;
  }
};

} // namespace

//===----------------------------------------------------------------------===//
// Address validation
//===----------------------------------------------------------------------===//

namespace {

bool isAddressInModule(char *base, char *addr) {
  auto *nt =
      static_cast<const ImageNtHeaders *>(::RtlImageNtHeader(base));
  if (!nt)
    return false;

  uptr addrVal = reinterpret_cast<uptr>(addr);
  uptr baseVal = reinterpret_cast<uptr>(base);
  if (addrVal < baseVal || addrVal >= baseVal + nt->OptionalHeader.SizeOfImage)
    return false;

  MemoryBasicInformation mbi;
  size_t returnLength = 0;
  if (!ntSuccess(::NtQueryVirtualMemory(ntCurrentProcess(), addr,
                                        kMemoryBasicInformation, &mbi,
                                        sizeof(mbi), &returnLength)) ||
      returnLength < sizeof(mbi))
    return false;

  return mbi.State == kMemCommit && mbi.AllocationBase == base;
}

} // namespace

//===----------------------------------------------------------------------===//
// Relocation application
//===----------------------------------------------------------------------===//

namespace {

[[noreturn]] void fastFail() {
  __builtin_trap();
  __builtin_unreachable();
}

[[noreturn]] void fatalError(const char *msg) {
  (void)msg;
  fastFail();
}

bool applyRelocV2(char *base, const PseudoRelocV2 *reloc, PageTracker &tracker) {
  char *symAddr = base + reloc->sym;
  char *targetAddr = base + reloc->target;
  unsigned long sizeBits = reloc->flags & 0xFF;

  if (!isAddressInModule(base, symAddr) ||
      !isAddressInModule(base, targetAddr) ||
      !isAddressInModule(base, targetAddr + (sizeBits / 8) - 1)) {
    fatalError("address outside module bounds");
  }

  void *actualAddr;
  __builtin_memcpy(&actualAddr, symAddr, sizeof(void *));
  ptrdiff_t delta = reinterpret_cast<char *>(actualAddr) - symAddr;

  if (!tracker.makeWritable(targetAddr, sizeBits / 8))
    return false;

  switch (sizeBits) {
  case 8: {
    int8_t val;
    __builtin_memcpy(&val, targetAddr, 1);
    val += static_cast<int8_t>(delta);
    __builtin_memcpy(targetAddr, &val, 1);
    break;
  }
  case 16: {
    int16_t val;
    __builtin_memcpy(&val, targetAddr, 2);
    val += static_cast<int16_t>(delta);
    __builtin_memcpy(targetAddr, &val, 2);
    break;
  }
  case 32: {
    int32_t val;
    __builtin_memcpy(&val, targetAddr, 4);
    long long newVal = static_cast<long long>(val) + delta;
    if (newVal < INT32_MIN || newVal > INT32_MAX)
      fastFail();
    val = static_cast<int32_t>(newVal);
    __builtin_memcpy(targetAddr, &val, 4);
    break;
  }
  case 64: {
    long long val;
    __builtin_memcpy(&val, targetAddr, 8);
    val += delta;
    __builtin_memcpy(targetAddr, &val, 8);
    break;
  }
  default:
    return false;
  }
  return true;
}

void doPseudoReloc(char *start, char *end, char *base) {
  if (start >= end || (end - start) < 8)
    return;

  PageTracker tracker;
  auto *header = reinterpret_cast<PseudoRelocHeader *>(start);

  if (header->magic1 == 0 && header->magic2 == 0) {
    // V2 format.
    if (header->version != 1)
      fatalError("unknown v2 protocol version");

    auto *reloc =
        reinterpret_cast<const PseudoRelocV2 *>(start + sizeof(PseudoRelocHeader));
    auto *relocEnd = reinterpret_cast<const PseudoRelocV2 *>(end);

    while (reloc < relocEnd) {
      if (!applyRelocV2(base, reloc, tracker))
        fatalError("relocation failed");
      ++reloc;
    }
  } else {
    // V1 format (legacy).
    auto *reloc = reinterpret_cast<const PseudoRelocV1 *>(start);
    auto *relocEnd = reinterpret_cast<const PseudoRelocV1 *>(end);

    while (reloc < relocEnd) {
      char *targetAddr = base + reloc->target;
      if (!isAddressInModule(base, targetAddr) ||
          !isAddressInModule(base, targetAddr + 3))
        fastFail();

      if (!tracker.makeWritable(targetAddr, 4))
        fatalError("page protection update failed");

      unsigned long val;
      __builtin_memcpy(&val, targetAddr, 4);
      val += reloc->addend;
      __builtin_memcpy(targetAddr, &val, 4);
      ++reloc;
    }
  }
}

} // namespace

//===----------------------------------------------------------------------===//
// Linker-generated symbols
//===----------------------------------------------------------------------===//

extern "C" {

char __attribute__((selectany)) __crt_pseudo_reloc_empty__[1] = {0};

extern char __RUNTIME_PSEUDO_RELOC_LIST__[];
extern char __RUNTIME_PSEUDO_RELOC_LIST_END__[];

volatile long __attribute__((selectany)) __pseudo_reloc_guard = 0;
}

#if defined(_M_IX86) || defined(__i386__)
#pragma comment(                                                               \
    linker,                                                                    \
    "/alternatename:__RUNTIME_PSEUDO_RELOC_LIST__=___crt_pseudo_reloc_empty__")
#pragma comment(                                                               \
    linker,                                                                    \
    "/alternatename:__RUNTIME_PSEUDO_RELOC_LIST_END__=___crt_pseudo_reloc_empty__")
#else
#pragma comment(                                                               \
    linker,                                                                    \
    "/alternatename:__RUNTIME_PSEUDO_RELOC_LIST__=__crt_pseudo_reloc_empty__")
#pragma comment(                                                               \
    linker,                                                                    \
    "/alternatename:__RUNTIME_PSEUDO_RELOC_LIST_END__=__crt_pseudo_reloc_empty__")
#endif

//===----------------------------------------------------------------------===//
// CRT initialization
//===----------------------------------------------------------------------===//

namespace {

void runPseudoRelocator() {
  if (__atomic_exchange_n(&__pseudo_reloc_guard, 1, __ATOMIC_ACQ_REL) != 0)
    return;
  void *imageBase = nullptr;
  // Resolve the image containing this runtime so DLL startup patches the DLL
  // itself instead of always falling back to the process executable.
  if (::RtlPcToFileHeader(reinterpret_cast<void *>(&runPseudoRelocator),
                          &imageBase) == nullptr ||
      imageBase == nullptr)
    fatalError("failed to resolve module base");
  char *base = static_cast<char *>(imageBase);
  doPseudoReloc(__RUNTIME_PSEUDO_RELOC_LIST__, __RUNTIME_PSEUDO_RELOC_LIST_END__,
                base);
}

int __cdecl pseudoRelocInit() {
  runPseudoRelocator();
  return 0;
}

} // namespace

using _PIFV = int(__cdecl *)(void);

extern "C" __attribute__((section(".CRT$XIB"), used)) _PIFV
    __pseudo_reloc_init_ptr =
    pseudoRelocInit;

#pragma comment(                                                               \
    linker, "/include:" CRT_PSEUDO_RELOC_SYM_PREFIX "_pei386_runtime_relocator")

extern "C" void _pei386_runtime_relocator(void) { runPseudoRelocator(); }

#endif // _WIN32_ITANIUM || __NTPOSIX__
