; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt -passes="default<O3>" -verify-each -S < %s | FileCheck %s

target triple = "x86_64-unknown-linux-gnu"

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)

define internal void @copy(ptr %dst, ptr %src) noinline {
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %dst, ptr align 8 %src, i64 16, i1 false)
  ret void
}

; Output promotion exposes the source load to ordinary input promotion. The
; helper then returns its argument. Attribute inference and value propagation
; eliminate the call without inlining it or recognizing a particular caller.
define i64 @local_value(i64 %x, i64 %y) {
; CHECK-LABEL: define {{[^@]+}}@local_value
; CHECK-SAME: (i64 [[X:%.*]], i64 [[Y:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[R:%.*]] = add i64 [[Y]], [[X]]
; CHECK-NEXT:    ret i64 [[R]]
;
  %src = alloca [2 x i64], align 8
  %dst = alloca [2 x i64], align 8
  store i64 %x, ptr %src, align 8
  %src1 = getelementptr i64, ptr %src, i64 1
  store i64 %y, ptr %src1, align 8
  call void @copy(ptr %dst, ptr %src)
  %dst1 = getelementptr i64, ptr %dst, i64 1
  %v = load i64, ptr %dst1, align 8
  %r = add i64 %x, %v
  ret i64 %r
}

; An escaping destination still needs the copy, but not the identity helper.
define void @external_storage(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@external_storage
; CHECK-SAME: (ptr writeonly captures(none) initializes((0, 16)) [[DST:%.*]], ptr readonly captures(none) [[SRC:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[SRC_VAL:%.*]] = load i128, ptr [[SRC]], align 8
; CHECK-NEXT:    store i128 [[SRC_VAL]], ptr [[DST]], align 8
; CHECK-NEXT:    ret void
;
  call void @copy(ptr %dst, ptr %src)
  ret void
}

; An unresolved indirect call retains its memory interface.
define i64 @indirect(ptr %manager, ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@indirect
; CHECK-SAME: (ptr readonly captures(none) [[MANAGER:%.*]], ptr [[DST:%.*]], ptr [[SRC:%.*]]) local_unnamed_addr {
; CHECK-NEXT:    tail call void [[MANAGER]](ptr [[DST]], ptr [[SRC]])
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[DST]], align 8
; CHECK-NEXT:    ret i64 [[V]]
;
  call void %manager(ptr %dst, ptr %src)
  %v = load i64, ptr %dst, align 8
  ret i64 %v
}
