//===-- Utils for wctype classification functions ---------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
// DO NOT EDIT MANUALLY.
// This file is generated by libc/utils/wctype_utils scripts.

#ifndef LLVM_LIBC_SRC___SUPPORT_WCTYPE_WCTYPE_CLASSIFICATION_UTILS_H
#define LLVM_LIBC_SRC___SUPPORT_WCTYPE_WCTYPE_CLASSIFICATION_UTILS_H

#include "hdr/stdint_proxy.h"
#include "hdr/types/wchar_t.h"
#include "src/__support/CPP/limits.h"
#include "src/__support/libc_assert.h"
#include "src/__support/macros/attributes.h"
#include "src/__support/macros/config.h"

namespace LIBC_NAMESPACE_DECL {

// Property flags for Unicode categories
enum PropertyFlag : uint8_t {
  UPPER = 1 << 0,
  LOWER = 1 << 1,
  ALPHA = 1 << 2,
  SPACE = 1 << 3,
  PRINT = 1 << 4,
  BLANK = 1 << 5,
  CNTRL = 1 << 6,
  PUNCT = 1 << 7,
};

static_assert(4352 <= cpp::numeric_limits<unsigned short>::max());
static_assert(39168 <= cpp::numeric_limits<unsigned short>::max());

LIBC_INLINE_VAR constexpr uint16_t LEVEL1_SIZE = 4352;
LIBC_INLINE_VAR constexpr uint16_t LEVEL2_SIZE = 39168;

// Level 1 table: indexed by (codepoint >> 8), stores level2 block offsets
extern const uint16_t LEVEL1[LEVEL1_SIZE];

// Level 2 table: blocks of 256 property flags
extern const uint8_t LEVEL2[LEVEL2_SIZE];

// Returns the Unicode property flag for a given wide character.
LIBC_INLINE uint8_t lookup_properties(const wchar_t wc) {
  // Out of Unicode range
  if (static_cast<uint32_t>(wc) > 0x10FFFF) {
    return 0;
  }

  uint16_t l1_idx = static_cast<uint16_t>(wc >> 8);
  LIBC_ASSERT(l1_idx < LEVEL1_SIZE);

  uint16_t l2_offset = LEVEL1[l1_idx];
  uint16_t l2_idx = l2_offset + (wc & 0xFF);
  LIBC_ASSERT(l2_idx < LEVEL2_SIZE);

  return LEVEL2[l2_idx];
}

//===----------------------------------------------------------------------===//
// Unicode case mapping tables (sorted {from, to} pairs for binary search)
//===----------------------------------------------------------------------===//

struct CasePair {
  char32_t from;
  char32_t to;
};

LIBC_INLINE_VAR constexpr CasePair upper_to_lower_table[] = {
#include "upper_to_lower.inc"
};

LIBC_INLINE_VAR constexpr CasePair lower_to_upper_table[] = {
#include "lower_to_upper.inc"
};

LIBC_INLINE_VAR constexpr size_t UPPER_TO_LOWER_SIZE =
    sizeof(upper_to_lower_table) / sizeof(CasePair);
LIBC_INLINE_VAR constexpr size_t LOWER_TO_UPPER_SIZE =
    sizeof(lower_to_upper_table) / sizeof(CasePair);

// Binary search over a sorted CasePair table. Returns the mapped codepoint,
// or the input unchanged if not found.
LIBC_INLINE constexpr wchar_t case_map_lookup(const CasePair *table,
                                               size_t table_size,
                                               wchar_t wc) {
  auto cp = static_cast<char32_t>(wc);
  size_t lo = 0, hi = table_size;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (table[mid].from < cp)
      lo = mid + 1;
    else if (table[mid].from > cp)
      hi = mid;
    else
      return static_cast<wchar_t>(table[mid].to);
  }
  return wc;
}

LIBC_INLINE constexpr wchar_t unicode_to_lower(wchar_t wc) {
  return case_map_lookup(upper_to_lower_table, UPPER_TO_LOWER_SIZE, wc);
}

LIBC_INLINE constexpr wchar_t unicode_to_upper(wchar_t wc) {
  return case_map_lookup(lower_to_upper_table, LOWER_TO_UPPER_SIZE, wc);
}

} // namespace LIBC_NAMESPACE_DECL

#endif // LLVM_LIBC_SRC___SUPPORT_WCTYPE_WCTYPE_CLASSIFICATION_UTILS_H
