; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt -passes=argpromotion -verify-each -S < %s | FileCheck %s

target triple = "x86_64-unknown-linux-gnu"

declare void @observe(ptr)
declare void @may_throw()
declare i32 @personality(...)

; Computation and control flow do not prevent output promotion. The last store
; must execute on every normal return, and must not move across an observation.
define internal void @computed(ptr %out, i32 %x) noinline {
; CHECK-LABEL: define {{[^@]+}}@computed
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[V:%.*]] = mul i32 [[X]], 7
; CHECK-NEXT:    ret i32 [[V]]
;
  %v = mul i32 %x, 7
  store i32 %v, ptr %out, align 1
  ret void
}

define void @call_computed(ptr %out, i32 %x) {
; CHECK-LABEL: define {{[^@]+}}@call_computed
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @computed(i32 [[X]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[OUT]], align 1
; CHECK-NEXT:    ret void
;
  tail call void @computed(ptr %out, i32 %x)
  ret void
}

define internal void @diamond(ptr %out, i32 %x, i1 %c) {
; CHECK-LABEL: define {{[^@]+}}@diamond
; CHECK-SAME: (i32 [[X:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:    br i1 [[C]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    [[A:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       right:
; CHECK-NEXT:    [[B:%.*]] = mul i32 [[X]], 3
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[A]], [[LEFT]] ], [ [[B]], [[RIGHT]] ]
; CHECK-NEXT:    ret i32 [[V]]
;
  br i1 %c, label %left, label %right
left:
  %a = add i32 %x, 1
  br label %exit
right:
  %b = mul i32 %x, 3
  br label %exit
exit:
  %v = phi i32 [ %a, %left ], [ %b, %right ]
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_diamond(ptr %out, i32 %x, i1 %c) {
; CHECK-LABEL: define {{[^@]+}}@call_diamond
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[X:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @diamond(i32 [[X]], i1 [[C]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  call void @diamond(ptr %out, i32 %x, i1 %c)
  ret void
}

; The input and output may alias: the load must still precede the store.
define internal void @alias(ptr %out, ptr %in) {
; CHECK-LABEL: define {{[^@]+}}@alias
; CHECK-SAME: (i32 [[IN_0_VAL:%.*]]) {
; CHECK-NEXT:    ret i32 [[IN_0_VAL]]
;
  %v = load i32, ptr %in, align 1
  store i32 %v, ptr %out, align 2
  ret void
}

define void @call_alias(ptr %p) {
; CHECK-LABEL: define {{[^@]+}}@call_alias
; CHECK-SAME: (ptr [[P:%.*]]) {
; CHECK-NEXT:    [[P_VAL:%.*]] = load i32, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @alias(i32 [[P_VAL]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[P]], align 2
; CHECK-NEXT:    ret void
;
  call void @alias(ptr %p, ptr %p)
  ret void
}

; A throw before the final store must still leave the destination unchanged.
define internal void @throw_before(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@throw_before
; CHECK-SAME: (i32 [[V:%.*]]) {
; CHECK-NEXT:    call void @may_throw()
; CHECK-NEXT:    ret i32 [[V]]
;
  call void @may_throw()
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_throw_before(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@call_throw_before
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @throw_before(i32 [[V]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  call void @throw_before(ptr %out, i32 %v)
  ret void
}

define internal void @read_output(ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@read_output
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[OUT]], align 4
; CHECK-NEXT:    [[INC:%.*]] = add i32 [[V]], 1
; CHECK-NEXT:    store i32 [[INC]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  %v = load i32, ptr %out, align 4
  %inc = add i32 %v, 1
  store i32 %inc, ptr %out, align 4
  ret void
}

define internal void @observed(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@observed
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    call void @observe(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  call void @observe(ptr %out)
  ret void
}

define internal void @captured(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@captured
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    call void @observe(ptr [[OUT]])
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  call void @observe(ptr %out)
  store i32 %v, ptr %out, align 4
  ret void
}

define internal void @conditional(ptr %out, i32 %v, i1 %c) {
; CHECK-LABEL: define {{[^@]+}}@conditional
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:    br i1 [[C]], label [[WRITE:%.*]], label [[SKIP:%.*]]
; CHECK:       write:
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
; CHECK:       skip:
; CHECK-NEXT:    ret void
;
  br i1 %c, label %write, label %skip
write:
  store i32 %v, ptr %out, align 4
  ret void
skip:
  ret void
}

define internal void @volatile_output(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@volatile_output
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store volatile i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 %v, ptr %out, align 4
  ret void
}

define internal void @atomic_output(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@atomic_output
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store atomic i32 [[V]], ptr [[OUT]] unordered, align 4
; CHECK-NEXT:    ret void
;
  store atomic i32 %v, ptr %out unordered, align 4
  ret void
}

define internal i32 @nonvoid(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@nonvoid
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
  store i32 %v, ptr %out, align 4
  ret i32 %v
}

define internal void @offset_output(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@offset_output
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    [[P:%.*]] = getelementptr i8, ptr [[OUT]], i64 4
; CHECK-NEXT:    store i32 [[V]], ptr [[P]], align 4
; CHECK-NEXT:    ret void
;
  %p = getelementptr i8, ptr %out, i64 4
  store i32 %v, ptr %p, align 4
  ret void
}

define void @negative_calls(ptr %p, i32 %v, i1 %c) {
; CHECK-LABEL: define {{[^@]+}}@negative_calls
; CHECK-SAME: (ptr [[P:%.*]], i32 [[V:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:    call void @read_output(ptr [[P]])
; CHECK-NEXT:    call void @observed(ptr [[P]], i32 [[V]])
; CHECK-NEXT:    call void @captured(ptr [[P]], i32 [[V]])
; CHECK-NEXT:    call void @conditional(ptr [[P]], i32 [[V]], i1 [[C]])
; CHECK-NEXT:    call void @volatile_output(ptr [[P]], i32 [[V]])
; CHECK-NEXT:    call void @atomic_output(ptr [[P]], i32 [[V]])
; CHECK-NEXT:    [[R:%.*]] = call i32 @nonvoid(ptr [[P]], i32 [[V]])
; CHECK-NEXT:    call void @offset_output(ptr [[P]], i32 [[R]])
; CHECK-NEXT:    ret void
;
  call void @read_output(ptr %p)
  call void @observed(ptr %p, i32 %v)
  call void @captured(ptr %p, i32 %v)
  call void @conditional(ptr %p, i32 %v, i1 %c)
  call void @volatile_output(ptr %p, i32 %v)
  call void @atomic_output(ptr %p, i32 %v)
  %r = call i32 @nonvoid(ptr %p, i32 %v)
  call void @offset_output(ptr %p, i32 %r)
  ret void
}

; A byval write is private to the callee; it must not become a caller store.
define internal void @byval_output(ptr byval(i32) align 4 %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@byval_output
; CHECK-SAME: (i32 [[OUT_0_VAL:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_byval(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@call_byval
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    [[OUT_VAL:%.*]] = load i32, ptr [[OUT]], align 4
; CHECK-NEXT:    call void @byval_output(i32 [[OUT_VAL]], i32 [[V]])
; CHECK-NEXT:    ret void
;
  call void @byval_output(ptr byval(i32) align 4 %out, i32 %v)
  ret void
}

; All callers must be supported, including a mixture of calls and invokes.
define internal void @invoked(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@invoked
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_invoked(ptr %out, i32 %v) personality ptr @personality {
; CHECK-LABEL: define {{[^@]+}}@call_invoked
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) personality ptr @personality {
; CHECK-NEXT:    call void @invoked(ptr [[OUT]], i32 [[V]])
; CHECK-NEXT:    invoke void @invoked(ptr [[OUT]], i32 [[V]])
; CHECK-NEXT:            to label [[NORMAL:%.*]] unwind label [[EXCEPTION:%.*]]
; CHECK:       normal:
; CHECK-NEXT:    ret void
; CHECK:       exception:
; CHECK-NEXT:    [[LP:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    resume { ptr, i32 } [[LP]]
;
  call void @invoked(ptr %out, i32 %v)
  invoke void @invoked(ptr %out, i32 %v) to label %normal unwind label %exception
normal:
  ret void
exception:
  %lp = landingpad { ptr, i32 } cleanup
  resume { ptr, i32 } %lp
}

define internal void @bundled(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@bundled
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_bundled(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@call_bundled
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    call void @bundled(ptr [[OUT]], i32 [[V]]) [ "deopt"(ptr [[OUT]]) ]
; CHECK-NEXT:    ret void
;
  call void @bundled(ptr %out, i32 %v) [ "deopt"(ptr %out) ]
  ret void
}

define internal void @musttail_output(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@musttail_output
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_musttail(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@call_musttail
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    musttail call void @musttail_output(ptr [[OUT]], i32 [[V]])
; CHECK-NEXT:    ret void
;
  musttail call void @musttail_output(ptr %out, i32 %v)
  ret void
}

@escaped = global ptr @address_taken
define internal void @address_taken(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@address_taken
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

define void @public_output(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@public_output
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

; Preserve non-temporal intent and propagate vector-width requirements even
; when the output value was already passed by value.
define internal void @vector_output(ptr %out, <4 x i32> %v) #0 {
; CHECK-LABEL: define {{[^@]+}}@vector_output
; CHECK-SAME: (<4 x i32> [[V:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    ret <4 x i32> [[V]]
;
  store <4 x i32> %v, ptr %out, align 16, !nontemporal !0
  ret void
}

define void @call_vector(ptr %out, <4 x i32> %v) #0 {
; CHECK-LABEL: define {{[^@]+}}@call_vector
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x i32> [[V:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i32> @vector_output(<4 x i32> [[V]])
; CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[OUT]], align 16, !nontemporal [[META0:![0-9]+]]
; CHECK-NEXT:    ret void
;
  call void @vector_output(ptr %out, <4 x i32> %v)
  ret void
}

define internal void @large_output(ptr %out, i256 %v) {
; CHECK-LABEL: define {{[^@]+}}@large_output
; CHECK-SAME: (ptr [[OUT:%.*]], i256 [[V:%.*]]) {
; CHECK-NEXT:    store i256 [[V]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
  store i256 %v, ptr %out, align 8
  ret void
}

define internal void @scalable_output(ptr %out, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define {{[^@]+}}@scalable_output
; CHECK-SAME: (ptr [[OUT:%.*]], <vscale x 4 x i32> [[V:%.*]]) {
; CHECK-NEXT:    store <vscale x 4 x i32> [[V]], ptr [[OUT]], align 16
; CHECK-NEXT:    ret void
;
  store <vscale x 4 x i32> %v, ptr %out, align 16
  ret void
}

define void @call_large(ptr %out, i256 %v, <vscale x 4 x i32> %sv) {
; CHECK-LABEL: define {{[^@]+}}@call_large
; CHECK-SAME: (ptr [[OUT:%.*]], i256 [[V:%.*]], <vscale x 4 x i32> [[SV:%.*]]) {
; CHECK-NEXT:    call void @large_output(ptr [[OUT]], i256 [[V]])
; CHECK-NEXT:    call void @scalable_output(ptr [[OUT]], <vscale x 4 x i32> [[SV]])
; CHECK-NEXT:    ret void
;
  call void @large_output(ptr %out, i256 %v)
  call void @scalable_output(ptr %out, <vscale x 4 x i32> %sv)
  ret void
}

define internal void @optnone_output(ptr %out, i32 %v) noinline optnone {
; CHECK-LABEL: define {{[^@]+}}@optnone_output
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store i32 %v, ptr %out, align 4
  ret void
}

define void @call_optnone(ptr %out, i32 %v) {
; CHECK-LABEL: define {{[^@]+}}@call_optnone
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[V:%.*]]) {
; CHECK-NEXT:    call void @optnone_output(ptr [[OUT]], i32 [[V]])
; CHECK-NEXT:    ret void
;
  call void @optnone_output(ptr %out, i32 %v)
  ret void
}

; An escaping destination value is not just an output memory location.
define internal void @self_output(ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@self_output
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    store ptr [[OUT]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
  store ptr %out, ptr %out, align 8
  ret void
}

define void @call_self(ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@call_self
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @self_output(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @self_output(ptr %out)
  ret void
}

attributes #0 = { "min-legal-vector-width"="0" }
!0 = !{i32 1}
