; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt -passes=argpromotion -verify-each -S < %s | FileCheck %s

target datalayout = "e-p:64:64-p1:128:128-ni:1"

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)

; Even a copy in the default address space can contain non-integral pointers.
; Do not replace it with an integer load and store.
define internal void @copy(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@copy
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[SRC]], i64 16, i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @call_copy(ptr %dst, ptr %src) {
; CHECK-LABEL: define {{[^@]+}}@call_copy
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @copy(ptr [[DST]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  call void @copy(ptr %dst, ptr %src)
  ret void
}
