; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=powerpc64le-linux-gnu -mcpu=pwr8 -verify-machineinstrs | FileCheck %s --check-prefix=LE
; RUN: llc < %s -mtriple=powerpc64-linux-gnu -mcpu=pwr8 -verify-machineinstrs | FileCheck %s --check-prefix=BE
; Partial-store forwarding requires target profitability approval.

define void @low_half(ptr %src, ptr %dst, i64 %x) {
; LE-LABEL: low_half:
; LE:       # %bb.0:
; LE-NEXT:    std 5, 0(3)
; LE-NEXT:    lxvd2x 0, 0, 3
; LE-NEXT:    stxvd2x 0, 0, 4
; LE-NEXT:    blr
;
; BE-LABEL: low_half:
; BE:       # %bb.0:
; BE-NEXT:    std 5, 0(3)
; BE-NEXT:    lxvd2x 0, 0, 3
; BE-NEXT:    stxvd2x 0, 0, 4
; BE-NEXT:    blr
  store i64 %x, ptr %src, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret void
}
define void @high_half(ptr %src, ptr %dst, i64 %x) {
; LE-LABEL: high_half:
; LE:       # %bb.0:
; LE-NEXT:    std 5, 8(3)
; LE-NEXT:    lxvd2x 0, 0, 3
; LE-NEXT:    stxvd2x 0, 0, 4
; LE-NEXT:    blr
;
; BE-LABEL: high_half:
; BE:       # %bb.0:
; BE-NEXT:    std 5, 8(3)
; BE-NEXT:    lxvd2x 0, 0, 3
; BE-NEXT:    stxvd2x 0, 0, 4
; BE-NEXT:    blr
  %field = getelementptr i8, ptr %src, i64 8
  store i64 %x, ptr %field, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret void
}
