; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=znver5 -verify-machineinstrs | FileCheck %s --check-prefix=SYSV
; RUN: llc < %s -mtriple=x86_64-windows-itanium -mcpu=znver5 -verify-machineinstrs | FileCheck %s --check-prefix=WIN
; Many split fragments would spill and require additional register saves.
; Keep the vector copy. Volatile stores preserve fragmentation in this test;
; the copy itself is non-volatile.
declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1)
define void @fragmented16(ptr %src, ptr %dst, i8 %value) {
; SYSV-LABEL: fragmented16:
; SYSV:       # %bb.0:
; SYSV-NEXT:    movb %dl, (%rdi)
; SYSV-NEXT:    movb %dl, 1(%rdi)
; SYSV-NEXT:    movb %dl, 2(%rdi)
; SYSV-NEXT:    movb %dl, 3(%rdi)
; SYSV-NEXT:    movb %dl, 4(%rdi)
; SYSV-NEXT:    movb %dl, 5(%rdi)
; SYSV-NEXT:    movb %dl, 6(%rdi)
; SYSV-NEXT:    movb %dl, 7(%rdi)
; SYSV-NEXT:    movb %dl, 8(%rdi)
; SYSV-NEXT:    movb %dl, 9(%rdi)
; SYSV-NEXT:    movb %dl, 10(%rdi)
; SYSV-NEXT:    movb %dl, 11(%rdi)
; SYSV-NEXT:    movb %dl, 12(%rdi)
; SYSV-NEXT:    movb %dl, 13(%rdi)
; SYSV-NEXT:    movb %dl, 14(%rdi)
; SYSV-NEXT:    movb %dl, 15(%rdi)
; SYSV-NEXT:    vmovups (%rdi), %xmm0
; SYSV-NEXT:    vmovups %xmm0, (%rsi)
; SYSV-NEXT:    retq
;
; WIN-LABEL: fragmented16:
; WIN:       # %bb.0:
; WIN-NEXT:    movb %r8b, (%rcx)
; WIN-NEXT:    movb %r8b, 1(%rcx)
; WIN-NEXT:    movb %r8b, 2(%rcx)
; WIN-NEXT:    movb %r8b, 3(%rcx)
; WIN-NEXT:    movb %r8b, 4(%rcx)
; WIN-NEXT:    movb %r8b, 5(%rcx)
; WIN-NEXT:    movb %r8b, 6(%rcx)
; WIN-NEXT:    movb %r8b, 7(%rcx)
; WIN-NEXT:    movb %r8b, 8(%rcx)
; WIN-NEXT:    movb %r8b, 9(%rcx)
; WIN-NEXT:    movb %r8b, 10(%rcx)
; WIN-NEXT:    movb %r8b, 11(%rcx)
; WIN-NEXT:    movb %r8b, 12(%rcx)
; WIN-NEXT:    movb %r8b, 13(%rcx)
; WIN-NEXT:    movb %r8b, 14(%rcx)
; WIN-NEXT:    movb %r8b, 15(%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  %p0 = getelementptr i8, ptr %src, i64 0
  store volatile i8 %value, ptr %p0, align 1
  %p1 = getelementptr i8, ptr %src, i64 1
  store volatile i8 %value, ptr %p1, align 1
  %p2 = getelementptr i8, ptr %src, i64 2
  store volatile i8 %value, ptr %p2, align 1
  %p3 = getelementptr i8, ptr %src, i64 3
  store volatile i8 %value, ptr %p3, align 1
  %p4 = getelementptr i8, ptr %src, i64 4
  store volatile i8 %value, ptr %p4, align 1
  %p5 = getelementptr i8, ptr %src, i64 5
  store volatile i8 %value, ptr %p5, align 1
  %p6 = getelementptr i8, ptr %src, i64 6
  store volatile i8 %value, ptr %p6, align 1
  %p7 = getelementptr i8, ptr %src, i64 7
  store volatile i8 %value, ptr %p7, align 1
  %p8 = getelementptr i8, ptr %src, i64 8
  store volatile i8 %value, ptr %p8, align 1
  %p9 = getelementptr i8, ptr %src, i64 9
  store volatile i8 %value, ptr %p9, align 1
  %p10 = getelementptr i8, ptr %src, i64 10
  store volatile i8 %value, ptr %p10, align 1
  %p11 = getelementptr i8, ptr %src, i64 11
  store volatile i8 %value, ptr %p11, align 1
  %p12 = getelementptr i8, ptr %src, i64 12
  store volatile i8 %value, ptr %p12, align 1
  %p13 = getelementptr i8, ptr %src, i64 13
  store volatile i8 %value, ptr %p13, align 1
  %p14 = getelementptr i8, ptr %src, i64 14
  store volatile i8 %value, ptr %p14, align 1
  %p15 = getelementptr i8, ptr %src, i64 15
  store volatile i8 %value, ptr %p15, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}
define void @fragmented32(ptr %src, ptr %dst, i8 %value) {
; SYSV-LABEL: fragmented32:
; SYSV:       # %bb.0:
; SYSV-NEXT:    movb %dl, (%rdi)
; SYSV-NEXT:    movb %dl, 1(%rdi)
; SYSV-NEXT:    movb %dl, 2(%rdi)
; SYSV-NEXT:    movb %dl, 3(%rdi)
; SYSV-NEXT:    movb %dl, 4(%rdi)
; SYSV-NEXT:    movb %dl, 5(%rdi)
; SYSV-NEXT:    movb %dl, 6(%rdi)
; SYSV-NEXT:    movb %dl, 7(%rdi)
; SYSV-NEXT:    movb %dl, 8(%rdi)
; SYSV-NEXT:    movb %dl, 9(%rdi)
; SYSV-NEXT:    movb %dl, 10(%rdi)
; SYSV-NEXT:    movb %dl, 11(%rdi)
; SYSV-NEXT:    movb %dl, 12(%rdi)
; SYSV-NEXT:    movb %dl, 13(%rdi)
; SYSV-NEXT:    movb %dl, 14(%rdi)
; SYSV-NEXT:    movb %dl, 15(%rdi)
; SYSV-NEXT:    movb %dl, 16(%rdi)
; SYSV-NEXT:    movb %dl, 17(%rdi)
; SYSV-NEXT:    movb %dl, 18(%rdi)
; SYSV-NEXT:    movb %dl, 19(%rdi)
; SYSV-NEXT:    movb %dl, 20(%rdi)
; SYSV-NEXT:    movb %dl, 21(%rdi)
; SYSV-NEXT:    movb %dl, 22(%rdi)
; SYSV-NEXT:    movb %dl, 23(%rdi)
; SYSV-NEXT:    movb %dl, 24(%rdi)
; SYSV-NEXT:    movb %dl, 25(%rdi)
; SYSV-NEXT:    movb %dl, 26(%rdi)
; SYSV-NEXT:    movb %dl, 27(%rdi)
; SYSV-NEXT:    movb %dl, 28(%rdi)
; SYSV-NEXT:    movb %dl, 29(%rdi)
; SYSV-NEXT:    movb %dl, 30(%rdi)
; SYSV-NEXT:    movb %dl, 31(%rdi)
; SYSV-NEXT:    vmovups (%rdi), %ymm0
; SYSV-NEXT:    vmovups %ymm0, (%rsi)
; SYSV-NEXT:    vzeroupper
; SYSV-NEXT:    retq
;
; WIN-LABEL: fragmented32:
; WIN:       # %bb.0:
; WIN-NEXT:    movb %r8b, (%rcx)
; WIN-NEXT:    movb %r8b, 1(%rcx)
; WIN-NEXT:    movb %r8b, 2(%rcx)
; WIN-NEXT:    movb %r8b, 3(%rcx)
; WIN-NEXT:    movb %r8b, 4(%rcx)
; WIN-NEXT:    movb %r8b, 5(%rcx)
; WIN-NEXT:    movb %r8b, 6(%rcx)
; WIN-NEXT:    movb %r8b, 7(%rcx)
; WIN-NEXT:    movb %r8b, 8(%rcx)
; WIN-NEXT:    movb %r8b, 9(%rcx)
; WIN-NEXT:    movb %r8b, 10(%rcx)
; WIN-NEXT:    movb %r8b, 11(%rcx)
; WIN-NEXT:    movb %r8b, 12(%rcx)
; WIN-NEXT:    movb %r8b, 13(%rcx)
; WIN-NEXT:    movb %r8b, 14(%rcx)
; WIN-NEXT:    movb %r8b, 15(%rcx)
; WIN-NEXT:    movb %r8b, 16(%rcx)
; WIN-NEXT:    movb %r8b, 17(%rcx)
; WIN-NEXT:    movb %r8b, 18(%rcx)
; WIN-NEXT:    movb %r8b, 19(%rcx)
; WIN-NEXT:    movb %r8b, 20(%rcx)
; WIN-NEXT:    movb %r8b, 21(%rcx)
; WIN-NEXT:    movb %r8b, 22(%rcx)
; WIN-NEXT:    movb %r8b, 23(%rcx)
; WIN-NEXT:    movb %r8b, 24(%rcx)
; WIN-NEXT:    movb %r8b, 25(%rcx)
; WIN-NEXT:    movb %r8b, 26(%rcx)
; WIN-NEXT:    movb %r8b, 27(%rcx)
; WIN-NEXT:    movb %r8b, 28(%rcx)
; WIN-NEXT:    movb %r8b, 29(%rcx)
; WIN-NEXT:    movb %r8b, 30(%rcx)
; WIN-NEXT:    movb %r8b, 31(%rcx)
; WIN-NEXT:    vmovups (%rcx), %ymm0
; WIN-NEXT:    vmovups %ymm0, (%rdx)
; WIN-NEXT:    vzeroupper
; WIN-NEXT:    retq
  %p0 = getelementptr i8, ptr %src, i64 0
  store volatile i8 %value, ptr %p0, align 1
  %p1 = getelementptr i8, ptr %src, i64 1
  store volatile i8 %value, ptr %p1, align 1
  %p2 = getelementptr i8, ptr %src, i64 2
  store volatile i8 %value, ptr %p2, align 1
  %p3 = getelementptr i8, ptr %src, i64 3
  store volatile i8 %value, ptr %p3, align 1
  %p4 = getelementptr i8, ptr %src, i64 4
  store volatile i8 %value, ptr %p4, align 1
  %p5 = getelementptr i8, ptr %src, i64 5
  store volatile i8 %value, ptr %p5, align 1
  %p6 = getelementptr i8, ptr %src, i64 6
  store volatile i8 %value, ptr %p6, align 1
  %p7 = getelementptr i8, ptr %src, i64 7
  store volatile i8 %value, ptr %p7, align 1
  %p8 = getelementptr i8, ptr %src, i64 8
  store volatile i8 %value, ptr %p8, align 1
  %p9 = getelementptr i8, ptr %src, i64 9
  store volatile i8 %value, ptr %p9, align 1
  %p10 = getelementptr i8, ptr %src, i64 10
  store volatile i8 %value, ptr %p10, align 1
  %p11 = getelementptr i8, ptr %src, i64 11
  store volatile i8 %value, ptr %p11, align 1
  %p12 = getelementptr i8, ptr %src, i64 12
  store volatile i8 %value, ptr %p12, align 1
  %p13 = getelementptr i8, ptr %src, i64 13
  store volatile i8 %value, ptr %p13, align 1
  %p14 = getelementptr i8, ptr %src, i64 14
  store volatile i8 %value, ptr %p14, align 1
  %p15 = getelementptr i8, ptr %src, i64 15
  store volatile i8 %value, ptr %p15, align 1
  %p16 = getelementptr i8, ptr %src, i64 16
  store volatile i8 %value, ptr %p16, align 1
  %p17 = getelementptr i8, ptr %src, i64 17
  store volatile i8 %value, ptr %p17, align 1
  %p18 = getelementptr i8, ptr %src, i64 18
  store volatile i8 %value, ptr %p18, align 1
  %p19 = getelementptr i8, ptr %src, i64 19
  store volatile i8 %value, ptr %p19, align 1
  %p20 = getelementptr i8, ptr %src, i64 20
  store volatile i8 %value, ptr %p20, align 1
  %p21 = getelementptr i8, ptr %src, i64 21
  store volatile i8 %value, ptr %p21, align 1
  %p22 = getelementptr i8, ptr %src, i64 22
  store volatile i8 %value, ptr %p22, align 1
  %p23 = getelementptr i8, ptr %src, i64 23
  store volatile i8 %value, ptr %p23, align 1
  %p24 = getelementptr i8, ptr %src, i64 24
  store volatile i8 %value, ptr %p24, align 1
  %p25 = getelementptr i8, ptr %src, i64 25
  store volatile i8 %value, ptr %p25, align 1
  %p26 = getelementptr i8, ptr %src, i64 26
  store volatile i8 %value, ptr %p26, align 1
  %p27 = getelementptr i8, ptr %src, i64 27
  store volatile i8 %value, ptr %p27, align 1
  %p28 = getelementptr i8, ptr %src, i64 28
  store volatile i8 %value, ptr %p28, align 1
  %p29 = getelementptr i8, ptr %src, i64 29
  store volatile i8 %value, ptr %p29, align 1
  %p30 = getelementptr i8, ptr %src, i64 30
  store volatile i8 %value, ptr %p30, align 1
  %p31 = getelementptr i8, ptr %src, i64 31
  store volatile i8 %value, ptr %p31, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
  ret void
}
