; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=x86-64 -verify-machineinstrs | FileCheck %s --check-prefix=SSE
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=znver5 -verify-machineinstrs | FileCheck %s --check-prefix=AVX

; The destination may overlap the source. Splitting must preserve all source
; reads before any destination write, including sub-word overlap.
declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1)

define void @unknown(ptr %src, ptr %out, i64 %value) {
; SSE-LABEL: unknown:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdx, (%rsi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: unknown:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %out, ptr align 8 %src, i64 16, i1 false)
  ret void
}

define void @wide(ptr %src, ptr %out, i64 %value) {
; SSE-LABEL: wide:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups 16(%rdi), %xmm1
; SSE-NEXT:    movups %xmm1, 16(%rsi)
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: wide:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovups 8(%rdi), %xmm0
; AVX-NEXT:    movq 24(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, (%rsi)
; AVX-NEXT:    movq %rax, 24(%rsi)
; AVX-NEXT:    vmovups %xmm0, 8(%rsi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %out, ptr align 8 %src, i64 32, i1 false)
  ret void
}

define void @forward(ptr %src, ptr %out, i64 %value) {
; SSE-LABEL: forward:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdx, 3(%rdi)
; SSE-NEXT:    movq %rax, 11(%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: forward:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, 3(%rdi)
; AVX-NEXT:    movq %rax, 11(%rdi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  %dst = getelementptr i8, ptr %src, i64 3
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 8 %src, i64 16, i1 false)
  ret void
}

define void @backward(ptr %src, ptr %out, i64 %value) {
; SSE-LABEL: backward:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdx, -3(%rdi)
; SSE-NEXT:    movq %rax, 5(%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: backward:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, -3(%rdi)
; AVX-NEXT:    movq %rax, 5(%rdi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  %dst = getelementptr i8, ptr %src, i64 -3
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 8 %src, i64 16, i1 false)
  ret void
}

; Without a visible blocking store, retain the vector copy.
define void @no_blocker(ptr %src, ptr %dst) {
; SSE-LABEL: no_blocker:
; SSE:       # %bb.0:
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: no_blocker:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 8 %src, i64 16, i1 false)
  ret void
}

; The ordered vector access must not be split even with disjoint parameters.
define void @volatile_load(ptr noalias %src, ptr noalias %dst, i64 %value) {
; SSE-LABEL: volatile_load:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: volatile_load:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  %v = load volatile <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret void
}

define void @volatile_store(ptr noalias %src, ptr noalias %dst, i64 %value) {
; SSE-LABEL: volatile_store:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: volatile_store:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store volatile <2 x i64> %v, ptr %dst, align 8
  ret void
}

; A blocker on only one predecessor must not change the copy on the other path.
define void @conditional_blocker(ptr %src, ptr %dst, i64 %value, i1 %cond) {
; SSE-LABEL: conditional_blocker:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    testb $1, %cl
; SSE-NEXT:    je .LBB7_2
; SSE-NEXT:  # %bb.1: # %update
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:  .LBB7_2: # %copy
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: conditional_blocker:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    testb $1, %cl
; AVX-NEXT:    je .LBB7_2
; AVX-NEXT:  # %bb.1: # %update
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:  .LBB7_2: # %copy
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
entry:
  br i1 %cond, label %update, label %copy
update:
  store i64 %value, ptr %src, align 8
  br label %copy
copy:
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Avoid expanding the instruction count when optimizing for size.
define void @size_copy(ptr %src, ptr %dst, i64 %value) optsize {
; SSE-LABEL: size_copy:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: size_copy:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
  store i64 %value, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Narrow, unaligned blockers create too many simultaneously live fragments.
; Keep the vector copy when the proposed split exceeds the register budget.
define void @byte_tail(ptr %src, ptr %dst, i8 %value) {
; SSE-LABEL: byte_tail:
; SSE:       # %bb.0:
; SSE-NEXT:    movb %dl, 31(%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups 16(%rdi), %xmm1
; SSE-NEXT:    movups %xmm1, 16(%rsi)
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: byte_tail:
; AVX:       # %bb.0:
; AVX-NEXT:    movb %dl, 31(%rdi)
; AVX-NEXT:    vmovups (%rdi), %ymm0
; AVX-NEXT:    vmovups %ymm0, (%rsi)
; AVX-NEXT:    vzeroupper
; AVX-NEXT:    retq
  %tail = getelementptr i8, ptr %src, i64 31
  store i8 %value, ptr %tail, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
  ret void
}

define void @unaligned_word(ptr %src, ptr %dst, i16 %value) {
; SSE-LABEL: unaligned_word:
; SSE:       # %bb.0:
; SSE-NEXT:    movw %dx, 7(%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups 16(%rdi), %xmm1
; SSE-NEXT:    movups %xmm1, 16(%rsi)
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: unaligned_word:
; AVX:       # %bb.0:
; AVX-NEXT:    movw %dx, 7(%rdi)
; AVX-NEXT:    vmovups (%rdi), %ymm0
; AVX-NEXT:    vmovups %ymm0, (%rsi)
; AVX-NEXT:    vzeroupper
; AVX-NEXT:    retq
  %field = getelementptr i8, ptr %src, i64 7
  store i16 %value, ptr %field, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
  ret void
}
