; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-pc-windows-msvc | FileCheck %s --check-prefix=MSVC
; Control Flow Guard is currently only available on Windows

; The guard dispatch function takes the target in RAX whichever convention the
; call uses, and leaves the argument registers to the target.

define x86_64_sysvcc i32 @sysv_call(ptr %p, i32 %a) nounwind {
; MSVC-LABEL: sysv_call:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    pushq %rax
; MSVC-NEXT:    movq %rdi, %rax
; MSVC-NEXT:    movl %esi, %edi
; MSVC-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; MSVC-NEXT:    popq %rcx
; MSVC-NEXT:    retq
;
; NTPOSIX-LABEL: sysv_call:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    pushq %rax
; NTPOSIX-NEXT:    movq %rdi, %rax
; NTPOSIX-NEXT:    movl %esi, %edi
; NTPOSIX-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; NTPOSIX-NEXT:    popq %rcx
; NTPOSIX-NEXT:    retq
entry:
  %r = call x86_64_sysvcc i32 %p(i32 %a, i32 %a)
  ret i32 %r
}

define x86_64_sysvcc i32 @sysv_tail_call(ptr %p, i32 %a) nounwind {
; MSVC-LABEL: sysv_tail_call:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    movq %rdi, %rax
; MSVC-NEXT:    movl %esi, %edi
; MSVC-NEXT:    rex64 jmpq *__guard_dispatch_icall_fptr(%rip) # TAILCALL
;
; NTPOSIX-LABEL: sysv_tail_call:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    movq %rdi, %rax
; NTPOSIX-NEXT:    movl %esi, %edi
; NTPOSIX-NEXT:    rex64 jmpq *__guard_dispatch_icall_fptr(%rip) # TAILCALL
entry:
  %r = tail call x86_64_sysvcc i32 %p(i32 %a, i32 %a)
  ret i32 %r
}

; The default convention: Win64 on msvc, System V on NT-POSIX.
define i32 @default_call(ptr %p, i32 %a) nounwind {
; MSVC-LABEL: default_call:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    subq $40, %rsp
; MSVC-NEXT:    movq %rcx, %rax
; MSVC-NEXT:    movl %edx, %ecx
; MSVC-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; MSVC-NEXT:    addq $40, %rsp
; MSVC-NEXT:    retq
;
; NTPOSIX-LABEL: default_call:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    pushq %rax
; NTPOSIX-NEXT:    movq %rdi, %rax
; NTPOSIX-NEXT:    movl %esi, %edi
; NTPOSIX-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; NTPOSIX-NEXT:    popq %rcx
; NTPOSIX-NEXT:    retq
entry:
  %r = call i32 %p(i32 %a, i32 %a)
  ret i32 %r
}

define win64cc i32 @win64_call(ptr %p, i32 %a) nounwind {
; MSVC-LABEL: win64_call:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    subq $40, %rsp
; MSVC-NEXT:    movq %rcx, %rax
; MSVC-NEXT:    movl %edx, %ecx
; MSVC-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; MSVC-NEXT:    addq $40, %rsp
; MSVC-NEXT:    retq
;
; NTPOSIX-LABEL: win64_call:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    subq $40, %rsp
; NTPOSIX-NEXT:    movq %rcx, %rax
; NTPOSIX-NEXT:    movl %edx, %ecx
; NTPOSIX-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; NTPOSIX-NEXT:    addq $40, %rsp
; NTPOSIX-NEXT:    retq
entry:
  %r = call win64cc i32 %p(i32 %a, i32 %a)
  ret i32 %r
}

!llvm.module.flags = !{!0}
!0 = !{i32 2, !"cfguard", i32 2}
