; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-pc-windows-msvc | FileCheck %s
; Control Flow Guard is currently only available on Windows

; The x86-64 guard check function uses RAX, R10 and R11 as scratch, so the
; arguments of the checked call are not kept in them across the check.

define i32 @args_across_check(ptr %p, i64 %a, i64 %b, i64 %c) nounwind {
; CHECK-LABEL: args_across_check:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %rsi
; CHECK-NEXT:    pushq %rdi
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    movq %r9, %rsi
; CHECK-NEXT:    movq %r8, %rdi
; CHECK-NEXT:    movq %rdx, %rbx
; CHECK-NEXT:    movq %rcx, %r14
; CHECK-NEXT:    callq *__guard_check_icall_fptr(%rip)
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    movq %rbx, %r8
; CHECK-NEXT:    callq *%r14
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %rdi
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    retq
entry:
  %r = call i32 %p(i64 %c, i64 %b, i64 %a)
  ret i32 %r
}

!llvm.module.flags = !{!0, !1}
!0 = !{i32 2, !"cfguard", i32 2}
!1 = !{i32 2, !"cfguard-mechanism", i32 1}
