; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-pc-windows-msvc | FileCheck %s --check-prefix=MSVC
; Control Flow Guard is currently only available on Windows

; A variadic call under the System V convention passes the number of vector
; registers it uses in AL, the low byte of RAX, in which the guard dispatch
; function takes the target. Such a call uses the guard check function, with
; the target in RCX, and sets its arguments, AL included, after the check.

define x86_64_sysvcc i32 @sysv_varargs(ptr %p, double %x) nounwind {
; MSVC-LABEL: sysv_varargs:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    subq $40, %rsp
; MSVC-NEXT:    movaps %xmm0, %xmm6
; MSVC-NEXT:    movq %rdi, %rcx
; MSVC-NEXT:    callq *__guard_check_icall_fptr(%rip)
; MSVC-NEXT:    movl $1, %edi
; MSVC-NEXT:    movaps %xmm6, %xmm0
; MSVC-NEXT:    movb $1, %al
; MSVC-NEXT:    callq *%rcx
; MSVC-NEXT:    addq $40, %rsp
; MSVC-NEXT:    retq
;
; NTPOSIX-LABEL: sysv_varargs:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    subq $40, %rsp
; NTPOSIX-NEXT:    movaps %xmm0, %xmm6
; NTPOSIX-NEXT:    movq %rdi, %rcx
; NTPOSIX-NEXT:    callq *__guard_check_icall_fptr(%rip)
; NTPOSIX-NEXT:    movl $1, %edi
; NTPOSIX-NEXT:    movaps %xmm6, %xmm0
; NTPOSIX-NEXT:    movb $1, %al
; NTPOSIX-NEXT:    callq *%rcx
; NTPOSIX-NEXT:    addq $40, %rsp
; NTPOSIX-NEXT:    retq
;
; NTPOSIX-O0-LABEL: sysv_varargs:
; NTPOSIX-O0:       # %bb.0: # %entry
; NTPOSIX-O0-NEXT:    subq $56, %rsp
; NTPOSIX-O0-NEXT:    movsd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %rdi, %rcx
; NTPOSIX-O0-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    callq *__guard_check_icall_fptr(%rip)
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; NTPOSIX-O0-NEXT:    movsd {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 8-byte Reload
; NTPOSIX-O0-NEXT:    # xmm0 = mem[0],zero
; NTPOSIX-O0-NEXT:    movl $1, %edi
; NTPOSIX-O0-NEXT:    movb $1, %al
; NTPOSIX-O0-NEXT:    callq *%rcx
; NTPOSIX-O0-NEXT:    addq $56, %rsp
; NTPOSIX-O0-NEXT:    retq
entry:
  %r = call x86_64_sysvcc i32 (i32, ...) %p(i32 1, double %x)
  ret i32 %r
}

; The default convention: Win64 on msvc, System V on NT-POSIX.
define i32 @default_varargs(ptr %p, double %x) nounwind {
; MSVC-LABEL: default_varargs:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    subq $40, %rsp
; MSVC-NEXT:    movq %rcx, %rax
; MSVC-NEXT:    movl $1, %ecx
; MSVC-NEXT:    movq %xmm1, %rdx
; MSVC-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; MSVC-NEXT:    addq $40, %rsp
; MSVC-NEXT:    retq
;
; NTPOSIX-LABEL: default_varargs:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    subq $40, %rsp
; NTPOSIX-NEXT:    movaps %xmm0, %xmm6
; NTPOSIX-NEXT:    movq %rdi, %rcx
; NTPOSIX-NEXT:    callq *__guard_check_icall_fptr(%rip)
; NTPOSIX-NEXT:    movl $1, %edi
; NTPOSIX-NEXT:    movaps %xmm6, %xmm0
; NTPOSIX-NEXT:    movb $1, %al
; NTPOSIX-NEXT:    callq *%rcx
; NTPOSIX-NEXT:    addq $40, %rsp
; NTPOSIX-NEXT:    retq
;
; NTPOSIX-O0-LABEL: default_varargs:
; NTPOSIX-O0:       # %bb.0: # %entry
; NTPOSIX-O0-NEXT:    subq $56, %rsp
; NTPOSIX-O0-NEXT:    movq %rdi, %rcx
; NTPOSIX-O0-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movsd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    callq *__guard_check_icall_fptr(%rip)
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; NTPOSIX-O0-NEXT:    movsd {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 8-byte Reload
; NTPOSIX-O0-NEXT:    # xmm0 = mem[0],zero
; NTPOSIX-O0-NEXT:    movl $1, %edi
; NTPOSIX-O0-NEXT:    movb $1, %al
; NTPOSIX-O0-NEXT:    callq *%rcx
; NTPOSIX-O0-NEXT:    addq $56, %rsp
; NTPOSIX-O0-NEXT:    retq
entry:
  %r = call i32 (i32, ...) %p(i32 1, double %x)
  ret i32 %r
}

define win64cc i32 @win64_varargs(ptr %p, double %x) nounwind {
; MSVC-LABEL: win64_varargs:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    subq $40, %rsp
; MSVC-NEXT:    movq %rcx, %rax
; MSVC-NEXT:    movl $1, %ecx
; MSVC-NEXT:    movq %xmm1, %rdx
; MSVC-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; MSVC-NEXT:    addq $40, %rsp
; MSVC-NEXT:    retq
;
; NTPOSIX-LABEL: win64_varargs:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    subq $40, %rsp
; NTPOSIX-NEXT:    movq %rcx, %rax
; NTPOSIX-NEXT:    movl $1, %ecx
; NTPOSIX-NEXT:    movq %xmm1, %rdx
; NTPOSIX-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; NTPOSIX-NEXT:    addq $40, %rsp
; NTPOSIX-NEXT:    retq
;
; NTPOSIX-O0-LABEL: win64_varargs:
; NTPOSIX-O0:       # %bb.0: # %entry
; NTPOSIX-O0-NEXT:    subq $40, %rsp
; NTPOSIX-O0-NEXT:    movaps %xmm1, %xmm0
; NTPOSIX-O0-NEXT:    movq %rcx, %rax
; NTPOSIX-O0-NEXT:    movl $1, %ecx
; NTPOSIX-O0-NEXT:    movaps %xmm0, %xmm1
; NTPOSIX-O0-NEXT:    movq %xmm0, %rdx
; NTPOSIX-O0-NEXT:    callq *__guard_dispatch_icall_fptr(%rip)
; NTPOSIX-O0-NEXT:    addq $40, %rsp
; NTPOSIX-O0-NEXT:    retq
entry:
  %r = call win64cc i32 (i32, ...) %p(i32 1, double %x)
  ret i32 %r
}

define x86_64_sysvcc i32 @sysv_musttail(ptr %p, ...) nounwind {
; MSVC-LABEL: sysv_musttail:
; MSVC:       # %bb.0: # %entry
; MSVC-NEXT:    pushq %r15
; MSVC-NEXT:    pushq %r14
; MSVC-NEXT:    pushq %r13
; MSVC-NEXT:    pushq %r12
; MSVC-NEXT:    pushq %rbx
; MSVC-NEXT:    subq $32, %rsp
; MSVC-NEXT:    movl %eax, %ebx
; MSVC-NEXT:    movaps %xmm5, %xmm8
; MSVC-NEXT:    movaps %xmm4, %xmm9
; MSVC-NEXT:    movaps %xmm3, %xmm10
; MSVC-NEXT:    movaps %xmm2, %xmm11
; MSVC-NEXT:    movaps %xmm1, %xmm12
; MSVC-NEXT:    movaps %xmm0, %xmm13
; MSVC-NEXT:    movq %r9, %r14
; MSVC-NEXT:    movq %r8, %r15
; MSVC-NEXT:    movq %rcx, %r12
; MSVC-NEXT:    movq %rdx, %r13
; MSVC-NEXT:    movq %rdi, %rcx
; MSVC-NEXT:    callq *__guard_check_icall_fptr(%rip)
; MSVC-NEXT:    movq %r13, %rdx
; MSVC-NEXT:    movq %r12, %rcx
; MSVC-NEXT:    movq %r15, %r8
; MSVC-NEXT:    movl %ebx, %eax
; MSVC-NEXT:    movq %r14, %r9
; MSVC-NEXT:    movaps %xmm13, %xmm0
; MSVC-NEXT:    movaps %xmm12, %xmm1
; MSVC-NEXT:    movaps %xmm11, %xmm2
; MSVC-NEXT:    movaps %xmm10, %xmm3
; MSVC-NEXT:    movaps %xmm9, %xmm4
; MSVC-NEXT:    movaps %xmm8, %xmm5
; MSVC-NEXT:    addq $32, %rsp
; MSVC-NEXT:    popq %rbx
; MSVC-NEXT:    popq %r12
; MSVC-NEXT:    popq %r13
; MSVC-NEXT:    popq %r14
; MSVC-NEXT:    popq %r15
; MSVC-NEXT:    rex64 jmpq *%rdi # TAILCALL
;
; NTPOSIX-LABEL: sysv_musttail:
; NTPOSIX:       # %bb.0: # %entry
; NTPOSIX-NEXT:    pushq %r15
; NTPOSIX-NEXT:    pushq %r14
; NTPOSIX-NEXT:    pushq %r13
; NTPOSIX-NEXT:    pushq %r12
; NTPOSIX-NEXT:    pushq %rbx
; NTPOSIX-NEXT:    subq $32, %rsp
; NTPOSIX-NEXT:    movl %eax, %ebx
; NTPOSIX-NEXT:    movaps %xmm5, %xmm8
; NTPOSIX-NEXT:    movaps %xmm4, %xmm9
; NTPOSIX-NEXT:    movaps %xmm3, %xmm10
; NTPOSIX-NEXT:    movaps %xmm2, %xmm11
; NTPOSIX-NEXT:    movaps %xmm1, %xmm12
; NTPOSIX-NEXT:    movaps %xmm0, %xmm13
; NTPOSIX-NEXT:    movq %r9, %r14
; NTPOSIX-NEXT:    movq %r8, %r15
; NTPOSIX-NEXT:    movq %rcx, %r12
; NTPOSIX-NEXT:    movq %rdx, %r13
; NTPOSIX-NEXT:    movq %rdi, %rcx
; NTPOSIX-NEXT:    callq *__guard_check_icall_fptr(%rip)
; NTPOSIX-NEXT:    movq %r13, %rdx
; NTPOSIX-NEXT:    movq %r12, %rcx
; NTPOSIX-NEXT:    movq %r15, %r8
; NTPOSIX-NEXT:    movl %ebx, %eax
; NTPOSIX-NEXT:    movq %r14, %r9
; NTPOSIX-NEXT:    movaps %xmm13, %xmm0
; NTPOSIX-NEXT:    movaps %xmm12, %xmm1
; NTPOSIX-NEXT:    movaps %xmm11, %xmm2
; NTPOSIX-NEXT:    movaps %xmm10, %xmm3
; NTPOSIX-NEXT:    movaps %xmm9, %xmm4
; NTPOSIX-NEXT:    movaps %xmm8, %xmm5
; NTPOSIX-NEXT:    addq $32, %rsp
; NTPOSIX-NEXT:    popq %rbx
; NTPOSIX-NEXT:    popq %r12
; NTPOSIX-NEXT:    popq %r13
; NTPOSIX-NEXT:    popq %r14
; NTPOSIX-NEXT:    popq %r15
; NTPOSIX-NEXT:    rex64 jmpq *%rdi # TAILCALL
;
; NTPOSIX-O0-LABEL: sysv_musttail:
; NTPOSIX-O0:       # %bb.0: # %entry
; NTPOSIX-O0-NEXT:    subq $200, %rsp
; NTPOSIX-O0-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %rdx, %rcx
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; NTPOSIX-O0-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %rdi, %rcx
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; NTPOSIX-O0-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NTPOSIX-O0-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NTPOSIX-O0-NEXT:    movaps %xmm1, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NTPOSIX-O0-NEXT:    movaps %xmm2, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NTPOSIX-O0-NEXT:    movaps %xmm3, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NTPOSIX-O0-NEXT:    movaps %xmm4, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NTPOSIX-O0-NEXT:    movaps %xmm5, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NTPOSIX-O0-NEXT:    movb %al, {{[-0-9]+}}(%r{{[sb]}}p) # 1-byte Spill
; NTPOSIX-O0-NEXT:    callq *__guard_check_icall_fptr(%rip)
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; NTPOSIX-O0-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; NTPOSIX-O0-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; NTPOSIX-O0-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; NTPOSIX-O0-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm3 # 16-byte Reload
; NTPOSIX-O0-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm4 # 16-byte Reload
; NTPOSIX-O0-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm5 # 16-byte Reload
; NTPOSIX-O0-NEXT:    movb {{[-0-9]+}}(%r{{[sb]}}p), %al # 1-byte Reload
; NTPOSIX-O0-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; NTPOSIX-O0-NEXT:    movq %r11, %rdi
; NTPOSIX-O0-NEXT:    addq $200, %rsp
; NTPOSIX-O0-NEXT:    rex64 jmpq *%r11 # TAILCALL
entry:
  %r = musttail call x86_64_sysvcc i32 (ptr, ...) %p(ptr %p, ...)
  ret i32 %r
}

!llvm.module.flags = !{!0}
!0 = !{i32 2, !"cfguard", i32 2}
