; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=x86-64 -verify-machineinstrs | FileCheck %s --check-prefix=SSE
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=znver5 -verify-machineinstrs | FileCheck %s --check-prefix=AVX
; RUN: llc < %s -mtriple=x86_64-windows-itanium -mcpu=znver5 -verify-machineinstrs | FileCheck %s --check-prefix=WIN
; Forward stored values only when the late copy plan has register headroom.

declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1)

define void @low_half(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: low_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdx, (%rsi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: low_half:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: low_half:
; WIN:       # %bb.0:
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    movq %r8, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @high_half(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: high_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, 8(%rdi)
; SSE-NEXT:    movq (%rdi), %rax
; SSE-NEXT:    movq %rax, (%rsi)
; SSE-NEXT:    movq %rdx, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: high_half:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, 8(%rdi)
; AVX-NEXT:    movq (%rdi), %rax
; AVX-NEXT:    movq %rdx, 8(%rsi)
; AVX-NEXT:    movq %rax, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: high_half:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, 8(%rcx)
; WIN-NEXT:    movq (%rcx), %rax
; WIN-NEXT:    movq %r8, 8(%rdx)
; WIN-NEXT:    movq %rax, (%rdx)
; WIN-NEXT:    retq
  %field = getelementptr i8, ptr %src, i64 8
  store i64 %x, ptr %field, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; An intervening possibly aliasing store must prevent forwarding %x.
define void @clobber(ptr %src, ptr %dst, ptr %other, i64 %x) {
; SSE-LABEL: clobber:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movq $0, (%rdx)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: clobber:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq $0, (%rdx)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: clobber:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq $0, (%r8)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 1
  store i64 0, ptr %other, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; The feeding store and the load must both be ordinary accesses.
define void @volatile_source(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: volatile_source:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq (%rdi), %rax
; SSE-NEXT:    movq 8(%rdi), %rcx
; SSE-NEXT:    movq %rax, (%rsi)
; SSE-NEXT:    movq %rcx, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: volatile_source:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq (%rdi), %rax
; AVX-NEXT:    movq 8(%rdi), %rcx
; AVX-NEXT:    movq %rax, (%rsi)
; AVX-NEXT:    movq %rcx, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: volatile_source:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    movq (%rcx), %rax
; WIN-NEXT:    movq 8(%rcx), %rcx
; WIN-NEXT:    movq %rax, (%rdx)
; WIN-NEXT:    movq %rcx, 8(%rdx)
; WIN-NEXT:    retq
  store volatile i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @atomic_source(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: atomic_source:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq (%rdi), %rax
; SSE-NEXT:    movq 8(%rdi), %rcx
; SSE-NEXT:    movq %rax, (%rsi)
; SSE-NEXT:    movq %rcx, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: atomic_source:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq 8(%rdi), %rcx
; AVX-NEXT:    movq (%rdi), %rax
; AVX-NEXT:    movq %rcx, 8(%rsi)
; AVX-NEXT:    movq %rax, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: atomic_source:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    movq (%rcx), %rax
; WIN-NEXT:    movq 8(%rcx), %rcx
; WIN-NEXT:    movq %rax, (%rdx)
; WIN-NEXT:    movq %rcx, 8(%rdx)
; WIN-NEXT:    retq
  store atomic i64 %x, ptr %src unordered, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; A store straddling the half boundary cannot supply a whole lane.
define void @middle_store(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: middle_store:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, 4(%rdi)
; SSE-NEXT:    movl (%rdi), %eax
; SSE-NEXT:    movl 12(%rdi), %ecx
; SSE-NEXT:    movl %eax, (%rsi)
; SSE-NEXT:    movq %rdx, 4(%rsi)
; SSE-NEXT:    movl %ecx, 12(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: middle_store:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, 4(%rdi)
; AVX-NEXT:    movl (%rdi), %eax
; AVX-NEXT:    movl 12(%rdi), %ecx
; AVX-NEXT:    movq %rdx, 4(%rsi)
; AVX-NEXT:    movl %eax, (%rsi)
; AVX-NEXT:    movl %ecx, 12(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: middle_store:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, 4(%rcx)
; WIN-NEXT:    movl (%rcx), %eax
; WIN-NEXT:    movl 12(%rcx), %ecx
; WIN-NEXT:    movq %r8, 4(%rdx)
; WIN-NEXT:    movl %eax, (%rdx)
; WIN-NEXT:    movl %ecx, 12(%rdx)
; WIN-NEXT:    retq
  %field = getelementptr i8, ptr %src, i64 4
  store i64 %x, ptr %field, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @size_copy(ptr %src, ptr %dst, i64 %x) optsize {
; SSE-LABEL: size_copy:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: size_copy:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: size_copy:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Preserve a vector value when it has another consumer.
define <2 x i64> @multiple_uses(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: multiple_uses:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: multiple_uses:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: multiple_uses:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret <2 x i64> %v
}

!0 = !{i32 1}

; Immediate stores have no register value to forward.
define void @zero_half(ptr %src, ptr %dst) {
; SSE-LABEL: zero_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movq $0, (%rdi)
; SSE-NEXT:    movq (%rdi), %rax
; SSE-NEXT:    movq 8(%rdi), %rcx
; SSE-NEXT:    movq %rax, (%rsi)
; SSE-NEXT:    movq %rcx, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: zero_half:
; AVX:       # %bb.0:
; AVX-NEXT:    movq $0, (%rdi)
; AVX-NEXT:    movq 8(%rdi), %rcx
; AVX-NEXT:    movq (%rdi), %rax
; AVX-NEXT:    movq %rcx, 8(%rsi)
; AVX-NEXT:    movq %rax, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: zero_half:
; WIN:       # %bb.0:
; WIN-NEXT:    movq $0, (%rcx)
; WIN-NEXT:    movq (%rcx), %rax
; WIN-NEXT:    movq 8(%rcx), %rcx
; WIN-NEXT:    movq %rax, (%rdx)
; WIN-NEXT:    movq %rcx, 8(%rdx)
; WIN-NEXT:    retq
  store i64 0, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Preserve live GPR values across the copy.
define void @gpr_pressure(ptr %src, ptr %dst, ptr %sink, i64 %x) {
; SSE-LABEL: gpr_pressure:
; SSE:       # %bb.0:
; SSE-NEXT:    pushq %rbx
; SSE-NEXT:    .cfi_def_cfa_offset 16
; SSE-NEXT:    .cfi_offset %rbx, -16
; SSE-NEXT:    movq 64(%rdi), %rax
; SSE-NEXT:    movq 72(%rdi), %r8
; SSE-NEXT:    movq 80(%rdi), %r9
; SSE-NEXT:    movq 88(%rdi), %r10
; SSE-NEXT:    movq 96(%rdi), %r11
; SSE-NEXT:    movq 104(%rdi), %rbx
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; SSE-NEXT:    movq %rcx, (%rsi)
; SSE-NEXT:    movlps %xmm0, 8(%rsi)
; SSE-NEXT:    movq %rax, (%rdx)
; SSE-NEXT:    movq %r8, 8(%rdx)
; SSE-NEXT:    movq %r9, 16(%rdx)
; SSE-NEXT:    movq %r10, 24(%rdx)
; SSE-NEXT:    movq %r11, 32(%rdx)
; SSE-NEXT:    movq %rbx, 40(%rdx)
; SSE-NEXT:    popq %rbx
; SSE-NEXT:    .cfi_def_cfa_offset 8
; SSE-NEXT:    retq
;
; AVX-LABEL: gpr_pressure:
; AVX:       # %bb.0:
; AVX-NEXT:    pushq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    .cfi_offset %rbx, -16
; AVX-NEXT:    vmovsd {{.*#+}} xmm0 = mem[0],zero
; AVX-NEXT:    movq 64(%rdi), %rax
; AVX-NEXT:    movq 72(%rdi), %r8
; AVX-NEXT:    movq 80(%rdi), %r9
; AVX-NEXT:    movq 88(%rdi), %r10
; AVX-NEXT:    movq 96(%rdi), %r11
; AVX-NEXT:    movq 104(%rdi), %rbx
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq %rcx, (%rsi)
; AVX-NEXT:    vmovlps %xmm0, 8(%rsi)
; AVX-NEXT:    movq %rax, (%rdx)
; AVX-NEXT:    movq %r8, 8(%rdx)
; AVX-NEXT:    movq %r9, 16(%rdx)
; AVX-NEXT:    movq %r10, 24(%rdx)
; AVX-NEXT:    movq %r11, 32(%rdx)
; AVX-NEXT:    movq %rbx, 40(%rdx)
; AVX-NEXT:    popq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 8
; AVX-NEXT:    retq
;
; WIN-LABEL: gpr_pressure:
; WIN:       # %bb.0:
; WIN-NEXT:    pushq %rsi
; WIN-NEXT:    .seh_pushreg %rsi
; WIN-NEXT:    pushq %rdi
; WIN-NEXT:    .seh_pushreg %rdi
; WIN-NEXT:    pushq %rbx
; WIN-NEXT:    .seh_pushreg %rbx
; WIN-NEXT:    .seh_endprologue
; WIN-NEXT:    vmovsd {{.*#+}} xmm0 = mem[0],zero
; WIN-NEXT:    movq 64(%rcx), %rax
; WIN-NEXT:    movq 72(%rcx), %r10
; WIN-NEXT:    movq 80(%rcx), %r11
; WIN-NEXT:    movq 88(%rcx), %rsi
; WIN-NEXT:    movq 96(%rcx), %rdi
; WIN-NEXT:    movq 104(%rcx), %rbx
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq %r9, (%rdx)
; WIN-NEXT:    vmovlps %xmm0, 8(%rdx)
; WIN-NEXT:    movq %rax, (%r8)
; WIN-NEXT:    movq %r10, 8(%r8)
; WIN-NEXT:    movq %r11, 16(%r8)
; WIN-NEXT:    movq %rsi, 24(%r8)
; WIN-NEXT:    movq %rdi, 32(%r8)
; WIN-NEXT:    movq %rbx, 40(%r8)
; WIN-NEXT:    .seh_startepilogue
; WIN-NEXT:    popq %rbx
; WIN-NEXT:    popq %rdi
; WIN-NEXT:    popq %rsi
; WIN-NEXT:    .seh_endepilogue
; WIN-NEXT:    retq
; WIN-NEXT:    .seh_endproc
  %p0 = getelementptr i8, ptr %src, i64 64
  %v0 = load i64, ptr %p0, align 8
  %p1 = getelementptr i8, ptr %src, i64 72
  %v1 = load i64, ptr %p1, align 8
  %p2 = getelementptr i8, ptr %src, i64 80
  %v2 = load i64, ptr %p2, align 8
  %p3 = getelementptr i8, ptr %src, i64 88
  %v3 = load i64, ptr %p3, align 8
  %p4 = getelementptr i8, ptr %src, i64 96
  %v4 = load i64, ptr %p4, align 8
  %p5 = getelementptr i8, ptr %src, i64 104
  %v5 = load i64, ptr %p5, align 8
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  %q0 = getelementptr i8, ptr %sink, i64 0
  store volatile i64 %v0, ptr %q0, align 8
  %q1 = getelementptr i8, ptr %sink, i64 8
  store volatile i64 %v1, ptr %q1, align 8
  %q2 = getelementptr i8, ptr %sink, i64 16
  store volatile i64 %v2, ptr %q2, align 8
  %q3 = getelementptr i8, ptr %sink, i64 24
  store volatile i64 %v3, ptr %q3, align 8
  %q4 = getelementptr i8, ptr %sink, i64 32
  store volatile i64 %v4, ptr %q4, align 8
  %q5 = getelementptr i8, ptr %sink, i64 40
  store volatile i64 %v5, ptr %q5, align 8
  ret void
}

; Preserve live SIMD values across the copy.
define void @simd_pressure(ptr %src, ptr %dst, ptr %sink, i64 %x) {
; SSE-LABEL: simd_pressure:
; SSE:       # %bb.0:
; SSE-NEXT:    movups 64(%rdi), %xmm0
; SSE-NEXT:    movups 80(%rdi), %xmm1
; SSE-NEXT:    movups 96(%rdi), %xmm2
; SSE-NEXT:    movups 112(%rdi), %xmm3
; SSE-NEXT:    movups 128(%rdi), %xmm4
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rcx, (%rsi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    movups %xmm0, (%rdx)
; SSE-NEXT:    movups %xmm1, 16(%rdx)
; SSE-NEXT:    movups %xmm2, 32(%rdx)
; SSE-NEXT:    movups %xmm3, 48(%rdx)
; SSE-NEXT:    movups %xmm4, 64(%rdx)
; SSE-NEXT:    retq
;
; AVX-LABEL: simd_pressure:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovups 64(%rdi), %xmm0
; AVX-NEXT:    vmovups 80(%rdi), %xmm1
; AVX-NEXT:    vmovups 96(%rdi), %xmm2
; AVX-NEXT:    vmovups 112(%rdi), %xmm3
; AVX-NEXT:    vmovups 128(%rdi), %xmm4
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq %rcx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    vmovups %xmm0, (%rdx)
; AVX-NEXT:    vmovups %xmm1, 16(%rdx)
; AVX-NEXT:    vmovups %xmm2, 32(%rdx)
; AVX-NEXT:    vmovups %xmm3, 48(%rdx)
; AVX-NEXT:    vmovups %xmm4, 64(%rdx)
; AVX-NEXT:    retq
;
; WIN-LABEL: simd_pressure:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovups 64(%rcx), %xmm0
; WIN-NEXT:    vmovups 80(%rcx), %xmm1
; WIN-NEXT:    vmovups 96(%rcx), %xmm2
; WIN-NEXT:    vmovups 112(%rcx), %xmm3
; WIN-NEXT:    vmovups 128(%rcx), %xmm4
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq %r9, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    vmovups %xmm0, (%r8)
; WIN-NEXT:    vmovups %xmm1, 16(%r8)
; WIN-NEXT:    vmovups %xmm2, 32(%r8)
; WIN-NEXT:    vmovups %xmm3, 48(%r8)
; WIN-NEXT:    vmovups %xmm4, 64(%r8)
; WIN-NEXT:    retq
  %p0 = getelementptr i8, ptr %src, i64 64
  %v0 = load <2 x i64>, ptr %p0, align 8
  %p1 = getelementptr i8, ptr %src, i64 80
  %v1 = load <2 x i64>, ptr %p1, align 8
  %p2 = getelementptr i8, ptr %src, i64 96
  %v2 = load <2 x i64>, ptr %p2, align 8
  %p3 = getelementptr i8, ptr %src, i64 112
  %v3 = load <2 x i64>, ptr %p3, align 8
  %p4 = getelementptr i8, ptr %src, i64 128
  %v4 = load <2 x i64>, ptr %p4, align 8
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  %q0 = getelementptr i8, ptr %sink, i64 0
  store volatile <2 x i64> %v0, ptr %q0, align 8
  %q1 = getelementptr i8, ptr %sink, i64 16
  store volatile <2 x i64> %v1, ptr %q1, align 8
  %q2 = getelementptr i8, ptr %sink, i64 32
  store volatile <2 x i64> %v2, ptr %q2, align 8
  %q3 = getelementptr i8, ptr %sink, i64 48
  store volatile <2 x i64> %v3, ptr %q3, align 8
  %q4 = getelementptr i8, ptr %sink, i64 64
  store volatile <2 x i64> %v4, ptr %q4, align 8
  ret void
}

; Do not replace a non-temporal vector load with an ordinary scalar access.
define void @nontemporal_load(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: nontemporal_load:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdx, (%rsi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: nontemporal_load:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovntdqa (%rdi), %xmm0
; AVX-NEXT:    vmovdqa %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: nontemporal_load:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovntdqa (%rcx), %xmm0
; WIN-NEXT:    vmovdqa %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 16
  %v = load <2 x i64>, ptr %src, align 16, !nontemporal !0
  store <2 x i64> %v, ptr %dst, align 16
  ret void
}

; The forwarded value is also the source address. Extending its use must clear
; the old kill, including when the other fragment loads through that register.
define void @source_is_address(ptr %src, ptr %dst) {
; SSE-LABEL: source_is_address:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdi, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdi, (%rsi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: source_is_address:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdi, (%rdi)
; AVX-NEXT:    movq %rdi, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: source_is_address:
; WIN:       # %bb.0:
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %rcx, (%rcx)
; WIN-NEXT:    movq %rcx, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    retq
  store ptr %src, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Values already live beyond the copy must not be counted twice.
define i64 @source_live_after(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: source_live_after:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rdx, (%rsi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    leaq 1(%rdx), %rax
; SSE-NEXT:    retq
;
; AVX-LABEL: source_live_after:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    leaq 1(%rdx), %rax
; AVX-NEXT:    retq
;
; WIN-LABEL: source_live_after:
; WIN:       # %bb.0:
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    movq %r8, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    leaq 1(%r8), %rax
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  %r = add i64 %x, 1
  ret i64 %r
}

define void @low_word(ptr %src, ptr %dst, i32 %x) {
; SSE-LABEL: low_word:
; SSE:       # %bb.0:
; SSE-NEXT:    movl %edx, (%rdi)
; SSE-NEXT:    movq 4(%rdi), %rax
; SSE-NEXT:    movl 12(%rdi), %ecx
; SSE-NEXT:    movl %edx, (%rsi)
; SSE-NEXT:    movq %rax, 4(%rsi)
; SSE-NEXT:    movl %ecx, 12(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: low_word:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 4(%rdi), %rax
; AVX-NEXT:    movl 12(%rdi), %ecx
; AVX-NEXT:    movl %edx, (%rdi)
; AVX-NEXT:    movl %edx, (%rsi)
; AVX-NEXT:    movq %rax, 4(%rsi)
; AVX-NEXT:    movl %ecx, 12(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: low_word:
; WIN:       # %bb.0:
; WIN-NEXT:    movl %r8d, (%rcx)
; WIN-NEXT:    movq 4(%rcx), %rax
; WIN-NEXT:    movl 12(%rcx), %ecx
; WIN-NEXT:    movl %r8d, (%rdx)
; WIN-NEXT:    movq %rax, 4(%rdx)
; WIN-NEXT:    movl %ecx, 12(%rdx)
; WIN-NEXT:    retq
  store i32 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @high_word(ptr %src, ptr %dst, i32 %x) {
; SSE-LABEL: high_word:
; SSE:       # %bb.0:
; SSE-NEXT:    movl %edx, 12(%rdi)
; SSE-NEXT:    movq (%rdi), %rax
; SSE-NEXT:    movl 8(%rdi), %ecx
; SSE-NEXT:    movq %rax, (%rsi)
; SSE-NEXT:    movl %ecx, 8(%rsi)
; SSE-NEXT:    movl %edx, 12(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: high_word:
; AVX:       # %bb.0:
; AVX-NEXT:    movl %edx, 12(%rdi)
; AVX-NEXT:    movq (%rdi), %rax
; AVX-NEXT:    movl 8(%rdi), %ecx
; AVX-NEXT:    movl %edx, 12(%rsi)
; AVX-NEXT:    movq %rax, (%rsi)
; AVX-NEXT:    movl %ecx, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: high_word:
; WIN:       # %bb.0:
; WIN-NEXT:    movl %r8d, 12(%rcx)
; WIN-NEXT:    movq (%rcx), %rax
; WIN-NEXT:    movl 8(%rcx), %ecx
; WIN-NEXT:    movl %r8d, 12(%rdx)
; WIN-NEXT:    movq %rax, (%rdx)
; WIN-NEXT:    movl %ecx, 8(%rdx)
; WIN-NEXT:    retq
  %p = getelementptr i8, ptr %src, i64 12
  store i32 %x, ptr %p, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @low_short(ptr %src, ptr %dst, i16 %x) {
; SSE-LABEL: low_short:
; SSE:       # %bb.0:
; SSE-NEXT:    movw %dx, (%rdi)
; SSE-NEXT:    movq 2(%rdi), %rax
; SSE-NEXT:    movl 10(%rdi), %ecx
; SSE-NEXT:    movzwl 14(%rdi), %edi
; SSE-NEXT:    movw %dx, (%rsi)
; SSE-NEXT:    movq %rax, 2(%rsi)
; SSE-NEXT:    movl %ecx, 10(%rsi)
; SSE-NEXT:    movw %di, 14(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: low_short:
; AVX:       # %bb.0:
; AVX-NEXT:    movw %dx, (%rdi)
; AVX-NEXT:    movq 2(%rdi), %rax
; AVX-NEXT:    movl 10(%rdi), %ecx
; AVX-NEXT:    movzwl 14(%rdi), %edi
; AVX-NEXT:    movw %dx, (%rsi)
; AVX-NEXT:    movq %rax, 2(%rsi)
; AVX-NEXT:    movl %ecx, 10(%rsi)
; AVX-NEXT:    movw %di, 14(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: low_short:
; WIN:       # %bb.0:
; WIN-NEXT:    movw %r8w, (%rcx)
; WIN-NEXT:    movq 2(%rcx), %rax
; WIN-NEXT:    movl 10(%rcx), %r9d
; WIN-NEXT:    movzwl 14(%rcx), %ecx
; WIN-NEXT:    movw %r8w, (%rdx)
; WIN-NEXT:    movq %rax, 2(%rdx)
; WIN-NEXT:    movl %r9d, 10(%rdx)
; WIN-NEXT:    movw %cx, 14(%rdx)
; WIN-NEXT:    retq
  store i16 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @low_byte(ptr %src, ptr %dst, i8 %x) {
; SSE-LABEL: low_byte:
; SSE:       # %bb.0:
; SSE-NEXT:    movb %dl, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: low_byte:
; AVX:       # %bb.0:
; AVX-NEXT:    movb %dl, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: low_byte:
; WIN:       # %bb.0:
; WIN-NEXT:    movb %r8b, (%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i8 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @vector_half(ptr %src, ptr %dst, <2 x i64> %x) {
; SSE-LABEL: vector_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movups %xmm0, (%rdi)
; SSE-NEXT:    movups 16(%rdi), %xmm1
; SSE-NEXT:    movups %xmm1, 16(%rsi)
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: vector_half:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovups 16(%rdi), %xmm1
; AVX-NEXT:    vmovups %xmm0, (%rdi)
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    vmovups %xmm1, 16(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: vector_half:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovaps (%r8), %xmm0
; WIN-NEXT:    vmovups 16(%rcx), %xmm1
; WIN-NEXT:    vmovups %xmm0, (%rcx)
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    vmovups %xmm1, 16(%rdx)
; WIN-NEXT:    retq
  store <2 x i64> %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 32, i1 false)
  ret void
}

define void @low_half_disjoint(ptr %src, ptr noalias %dst, i64 %x) {
; SSE-LABEL: low_half_disjoint:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq %rdx, (%rsi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: low_half_disjoint:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, (%rsi)
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: low_half_disjoint:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    movq %r8, (%rdx)
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @gpr_pressure_disjoint(ptr %src, ptr noalias %dst, ptr %sink, i64 %x) {
; SSE-LABEL: gpr_pressure_disjoint:
; SSE:       # %bb.0:
; SSE-NEXT:    pushq %rbx
; SSE-NEXT:    .cfi_def_cfa_offset 16
; SSE-NEXT:    .cfi_offset %rbx, -16
; SSE-NEXT:    movq 64(%rdi), %rax
; SSE-NEXT:    movq 72(%rdi), %r8
; SSE-NEXT:    movq 80(%rdi), %r9
; SSE-NEXT:    movq 88(%rdi), %r10
; SSE-NEXT:    movq 96(%rdi), %r11
; SSE-NEXT:    movq 104(%rdi), %rbx
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movq %rcx, (%rsi)
; SSE-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; SSE-NEXT:    movlps %xmm0, 8(%rsi)
; SSE-NEXT:    movq %rax, (%rdx)
; SSE-NEXT:    movq %r8, 8(%rdx)
; SSE-NEXT:    movq %r9, 16(%rdx)
; SSE-NEXT:    movq %r10, 24(%rdx)
; SSE-NEXT:    movq %r11, 32(%rdx)
; SSE-NEXT:    movq %rbx, 40(%rdx)
; SSE-NEXT:    popq %rbx
; SSE-NEXT:    .cfi_def_cfa_offset 8
; SSE-NEXT:    retq
;
; AVX-LABEL: gpr_pressure_disjoint:
; AVX:       # %bb.0:
; AVX-NEXT:    pushq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    .cfi_offset %rbx, -16
; AVX-NEXT:    movq 64(%rdi), %rax
; AVX-NEXT:    movq 72(%rdi), %r8
; AVX-NEXT:    movq 80(%rdi), %r9
; AVX-NEXT:    movq 88(%rdi), %r10
; AVX-NEXT:    movq 96(%rdi), %r11
; AVX-NEXT:    movq 104(%rdi), %rbx
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq %rcx, (%rsi)
; AVX-NEXT:    vmovsd {{.*#+}} xmm0 = mem[0],zero
; AVX-NEXT:    vmovlps %xmm0, 8(%rsi)
; AVX-NEXT:    movq %rax, (%rdx)
; AVX-NEXT:    movq %r8, 8(%rdx)
; AVX-NEXT:    movq %r9, 16(%rdx)
; AVX-NEXT:    movq %r10, 24(%rdx)
; AVX-NEXT:    movq %r11, 32(%rdx)
; AVX-NEXT:    movq %rbx, 40(%rdx)
; AVX-NEXT:    popq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 8
; AVX-NEXT:    retq
;
; WIN-LABEL: gpr_pressure_disjoint:
; WIN:       # %bb.0:
; WIN-NEXT:    pushq %rsi
; WIN-NEXT:    .seh_pushreg %rsi
; WIN-NEXT:    pushq %rdi
; WIN-NEXT:    .seh_pushreg %rdi
; WIN-NEXT:    pushq %rbx
; WIN-NEXT:    .seh_pushreg %rbx
; WIN-NEXT:    .seh_endprologue
; WIN-NEXT:    movq 64(%rcx), %rax
; WIN-NEXT:    movq 72(%rcx), %r10
; WIN-NEXT:    movq 80(%rcx), %r11
; WIN-NEXT:    movq 88(%rcx), %rsi
; WIN-NEXT:    movq 96(%rcx), %rdi
; WIN-NEXT:    movq 104(%rcx), %rbx
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq %r9, (%rdx)
; WIN-NEXT:    vmovsd {{.*#+}} xmm0 = mem[0],zero
; WIN-NEXT:    vmovlps %xmm0, 8(%rdx)
; WIN-NEXT:    movq %rax, (%r8)
; WIN-NEXT:    movq %r10, 8(%r8)
; WIN-NEXT:    movq %r11, 16(%r8)
; WIN-NEXT:    movq %rsi, 24(%r8)
; WIN-NEXT:    movq %rdi, 32(%r8)
; WIN-NEXT:    movq %rbx, 40(%r8)
; WIN-NEXT:    .seh_startepilogue
; WIN-NEXT:    popq %rbx
; WIN-NEXT:    popq %rdi
; WIN-NEXT:    popq %rsi
; WIN-NEXT:    .seh_endepilogue
; WIN-NEXT:    retq
; WIN-NEXT:    .seh_endproc
  %p0 = getelementptr i8, ptr %src, i64 64
  %v0 = load i64, ptr %p0, align 8
  %p1 = getelementptr i8, ptr %src, i64 72
  %v1 = load i64, ptr %p1, align 8
  %p2 = getelementptr i8, ptr %src, i64 80
  %v2 = load i64, ptr %p2, align 8
  %p3 = getelementptr i8, ptr %src, i64 88
  %v3 = load i64, ptr %p3, align 8
  %p4 = getelementptr i8, ptr %src, i64 96
  %v4 = load i64, ptr %p4, align 8
  %p5 = getelementptr i8, ptr %src, i64 104
  %v5 = load i64, ptr %p5, align 8
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  %q0 = getelementptr i8, ptr %sink, i64 0
  store volatile i64 %v0, ptr %q0, align 8
  %q1 = getelementptr i8, ptr %sink, i64 8
  store volatile i64 %v1, ptr %q1, align 8
  %q2 = getelementptr i8, ptr %sink, i64 16
  store volatile i64 %v2, ptr %q2, align 8
  %q3 = getelementptr i8, ptr %sink, i64 24
  store volatile i64 %v3, ptr %q3, align 8
  %q4 = getelementptr i8, ptr %sink, i64 32
  store volatile i64 %v4, ptr %q4, align 8
  %q5 = getelementptr i8, ptr %sink, i64 40
  store volatile i64 %v5, ptr %q5, align 8
  ret void
}
