; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx -verify-machineinstrs < %s | FileCheck %s

; Preserve source alignment independently of the common transfer alignment.
; The pointers have no alignment attributes: the guarantee is on the intrinsic.
define void @copy_src_aligned(ptr %dst, ptr %src) {
; CHECK-LABEL: copy_src_aligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovaps (%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
  ret void
}

define void @move_src_aligned(ptr %dst, ptr %src) {
; CHECK-LABEL: move_src_aligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovaps (%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
  ret void
}

define void @inline_src_aligned(ptr %dst, ptr %src) {
; CHECK-LABEL: inline_src_aligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovaps (%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memcpy.inline.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 16, i1 false)
  ret void
}

; The overlapping tail access must use alignment at its offset, not at the base.
define void @copy_tail(ptr %dst, ptr %src) {
; CHECK-LABEL: copy_tail:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovups 12(%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, 12(%rdi)
; CHECK-NEXT:    vmovaps (%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 28, i1 false)
  ret void
}

define void @move_tail(ptr %dst, ptr %src) {
; CHECK-LABEL: move_tail:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovaps (%rsi), %xmm0
; CHECK-NEXT:    vmovups 12(%rsi), %xmm1
; CHECK-NEXT:    vmovups %xmm1, 12(%rdi)
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 28, i1 false)
  ret void
}

; A destination guarantee must not be used to align the source load.
define void @unaligned_source(ptr %dst, ptr %src) {
; CHECK-LABEL: unaligned_source:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovups (%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %dst, ptr align 1 %src, i64 16, i1 false)
  ret void
}

define void @both_unaligned(ptr %dst, ptr %src) {
; CHECK-LABEL: both_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovups (%rsi), %xmm0
; CHECK-NEXT:    vmovups %xmm0, (%rdi)
; CHECK-NEXT:    retq
  call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i64 16, i1 false)
  ret void
}

; A zero-length transfer must not gain an access.
define void @zero_length(ptr %dst, ptr %src) {
; CHECK-LABEL: zero_length:
; CHECK:       # %bb.0:
; CHECK-NEXT:    retq
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 16 %src, i64 0, i1 false)
  ret void
}

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)
declare void @llvm.memcpy.inline.p0.p0.i64(ptr, ptr, i64 immarg, i1 immarg)
declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1 immarg)
