; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=x86-64 -x86-disable-avoid-SFB -verify-machineinstrs | FileCheck %s --check-prefix=SSE
; RUN: llc < %s -mtriple=x86_64-linux -mcpu=znver5 -x86-disable-avoid-SFB -verify-machineinstrs | FileCheck %s --check-prefix=AVX
; RUN: llc < %s -mtriple=x86_64-windows-itanium -mcpu=znver5 -x86-disable-avoid-SFB -verify-machineinstrs | FileCheck %s --check-prefix=WIN
; Exercise the earlier combine independently of the machine-level SFB pass.

declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1)

define void @low_half(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: low_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    movq %rdx, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: low_half:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    movq %rdx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: low_half:
; WIN:       # %bb.0:
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    movq %r8, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @high_half(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: high_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, 8(%rdi)
; SSE-NEXT:    movq (%rdi), %rax
; SSE-NEXT:    movq %rdx, 8(%rsi)
; SSE-NEXT:    movq %rax, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: high_half:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, 8(%rdi)
; AVX-NEXT:    movq (%rdi), %rax
; AVX-NEXT:    movq %rdx, 8(%rsi)
; AVX-NEXT:    movq %rax, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: high_half:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, 8(%rcx)
; WIN-NEXT:    movq (%rcx), %rax
; WIN-NEXT:    movq %r8, 8(%rdx)
; WIN-NEXT:    movq %rax, (%rdx)
; WIN-NEXT:    retq
  %field = getelementptr i8, ptr %src, i64 8
  store i64 %x, ptr %field, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; An intervening possibly aliasing store must prevent forwarding %x.
define void @clobber(ptr %src, ptr %dst, ptr %other, i64 %x) {
; SSE-LABEL: clobber:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movq $0, (%rdx)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: clobber:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq $0, (%rdx)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: clobber:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq $0, (%r8)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 1
  store i64 0, ptr %other, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; The feeding store and the load must both be ordinary accesses.
define void @volatile_source(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: volatile_source:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: volatile_source:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: volatile_source:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store volatile i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @atomic_source(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: atomic_source:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: atomic_source:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: atomic_source:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store atomic i64 %x, ptr %src unordered, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; A store straddling the half boundary cannot supply a whole lane.
define void @middle_store(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: middle_store:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, 4(%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: middle_store:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, 4(%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: middle_store:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, 4(%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  %field = getelementptr i8, ptr %src, i64 4
  store i64 %x, ptr %field, align 1
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

define void @size_copy(ptr %src, ptr %dst, i64 %x) optsize {
; SSE-LABEL: size_copy:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movups (%rdi), %xmm0
; SSE-NEXT:    movups %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: size_copy:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovups (%rdi), %xmm0
; AVX-NEXT:    vmovups %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: size_copy:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovups (%rcx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Preserve a vector value when it has another consumer.
define <2 x i64> @multiple_uses(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: multiple_uses:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movq {{.*#+}} xmm1 = mem[0],zero
; SSE-NEXT:    movq %rdx, %xmm0
; SSE-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SSE-NEXT:    movdqu %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: multiple_uses:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovq {{.*#+}} xmm0 = mem[0],zero
; AVX-NEXT:    vmovq %rdx, %xmm1
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; AVX-NEXT:    vmovdqu %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: multiple_uses:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovq {{.*#+}} xmm0 = mem[0],zero
; WIN-NEXT:    vmovq %r8, %xmm1
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; WIN-NEXT:    vmovdqu %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 8
  %v = load <2 x i64>, ptr %src, align 8
  store <2 x i64> %v, ptr %dst, align 8
  ret <2 x i64> %v
}

; This also applies when the loaded value is not a copy source.
define <2 x i64> @vector_result(ptr %src, i64 %x) {
; SSE-LABEL: vector_result:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rsi, (%rdi)
; SSE-NEXT:    movq {{.*#+}} xmm1 = mem[0],zero
; SSE-NEXT:    movq %rsi, %xmm0
; SSE-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SSE-NEXT:    retq
;
; AVX-LABEL: vector_result:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovq {{.*#+}} xmm0 = mem[0],zero
; AVX-NEXT:    vmovq %rsi, %xmm1
; AVX-NEXT:    movq %rsi, (%rdi)
; AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; AVX-NEXT:    retq
;
; WIN-LABEL: vector_result:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovq {{.*#+}} xmm0 = mem[0],zero
; WIN-NEXT:    vmovq %rdx, %xmm1
; WIN-NEXT:    movq %rdx, (%rcx)
; WIN-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 8
  %v = load <2 x i64>, ptr %src, align 8
  ret <2 x i64> %v
}

; Scalar-store selection is independent of forwarding.
define void @scalar_pair(ptr %dst, i64 %x, i64 %y) {
; SSE-LABEL: scalar_pair:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, 8(%rdi)
; SSE-NEXT:    movq %rsi, (%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: scalar_pair:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, 8(%rdi)
; AVX-NEXT:    movq %rsi, (%rdi)
; AVX-NEXT:    retq
;
; WIN-LABEL: scalar_pair:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, 8(%rcx)
; WIN-NEXT:    movq %rdx, (%rcx)
; WIN-NEXT:    retq
  %a = insertelement <2 x i64> poison, i64 %x, i32 0
  %b = insertelement <2 x i64> %a, i64 %y, i32 1
  store <2 x i64> %b, ptr %dst, align 1
  ret void
}

; Splats and values already in vector registers retain vector stores.
define void @splat(ptr %dst, i64 %x) {
; SSE-LABEL: splat:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rsi, %xmm0
; SSE-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[0,1,0,1]
; SSE-NEXT:    movdqu %xmm0, (%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: splat:
; AVX:       # %bb.0:
; AVX-NEXT:    vpbroadcastq %rsi, %xmm0
; AVX-NEXT:    vmovdqu %xmm0, (%rdi)
; AVX-NEXT:    retq
;
; WIN-LABEL: splat:
; WIN:       # %bb.0:
; WIN-NEXT:    vpbroadcastq %rdx, %xmm0
; WIN-NEXT:    vmovdqu %xmm0, (%rcx)
; WIN-NEXT:    retq
  %a = insertelement <2 x i64> poison, i64 %x, i32 0
  %b = insertelement <2 x i64> %a, i64 %x, i32 1
  store <2 x i64> %b, ptr %dst, align 1
  ret void
}

define void @vector_input(ptr %dst, <2 x i64> %x) {
; SSE-LABEL: vector_input:
; SSE:       # %bb.0:
; SSE-NEXT:    movups %xmm0, (%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: vector_input:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovups %xmm0, (%rdi)
; AVX-NEXT:    retq
;
; WIN-LABEL: vector_input:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovaps (%rdx), %xmm0
; WIN-NEXT:    vmovups %xmm0, (%rcx)
; WIN-NEXT:    retq
  store <2 x i64> %x, ptr %dst, align 1
  ret void
}

define void @volatile_pair(ptr %dst, i64 %x, i64 %y) {
; SSE-LABEL: volatile_pair:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, %xmm0
; SSE-NEXT:    movq %rsi, %xmm1
; SSE-NEXT:    punpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; SSE-NEXT:    movdqa %xmm1, (%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: volatile_pair:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovq %rdx, %xmm0
; AVX-NEXT:    vmovq %rsi, %xmm1
; AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; AVX-NEXT:    vmovdqa %xmm0, (%rdi)
; AVX-NEXT:    retq
;
; WIN-LABEL: volatile_pair:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovq %r8, %xmm0
; WIN-NEXT:    vmovq %rdx, %xmm1
; WIN-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; WIN-NEXT:    vmovdqa %xmm0, (%rcx)
; WIN-NEXT:    retq
  %a = insertelement <2 x i64> poison, i64 %x, i32 0
  %b = insertelement <2 x i64> %a, i64 %y, i32 1
  store volatile <2 x i64> %b, ptr %dst, align 16
  ret void
}

define void @nontemporal_pair(ptr %dst, i64 %x, i64 %y) {
; SSE-LABEL: nontemporal_pair:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, %xmm0
; SSE-NEXT:    movq %rsi, %xmm1
; SSE-NEXT:    punpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; SSE-NEXT:    movntdq %xmm1, (%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: nontemporal_pair:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovq %rdx, %xmm0
; AVX-NEXT:    vmovq %rsi, %xmm1
; AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; AVX-NEXT:    vmovntdq %xmm0, (%rdi)
; AVX-NEXT:    retq
;
; WIN-LABEL: nontemporal_pair:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovq %r8, %xmm0
; WIN-NEXT:    vmovq %rdx, %xmm1
; WIN-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; WIN-NEXT:    vmovntdq %xmm0, (%rcx)
; WIN-NEXT:    retq
  %a = insertelement <2 x i64> poison, i64 %x, i32 0
  %b = insertelement <2 x i64> %a, i64 %y, i32 1
  store <2 x i64> %b, ptr %dst, align 16, !nontemporal !0
  ret void
}
!0 = !{i32 1}

; A constant half can use a scalar store, without reconstructing a vector.
define void @zero_half(ptr %src, ptr %dst) {
; SSE-LABEL: zero_half:
; SSE:       # %bb.0:
; SSE-NEXT:    movq $0, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    movq $0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: zero_half:
; AVX:       # %bb.0:
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq $0, (%rdi)
; AVX-NEXT:    movq $0, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: zero_half:
; WIN:       # %bb.0:
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq $0, (%rcx)
; WIN-NEXT:    movq $0, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    retq
  store i64 0, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Leave all-constant vectors to the existing constant-store lowering.
define void @constant_pair(ptr %dst) {
; SSE-LABEL: constant_pair:
; SSE:       # %bb.0:
; SSE-NEXT:    movaps {{.*#+}} xmm0 = [123456789012345,987654321098765]
; SSE-NEXT:    movups %xmm0, (%rdi)
; SSE-NEXT:    retq
;
; AVX-LABEL: constant_pair:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovaps {{.*#+}} xmm0 = [123456789012345,987654321098765]
; AVX-NEXT:    vmovups %xmm0, (%rdi)
; AVX-NEXT:    retq
;
; WIN-LABEL: constant_pair:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovaps {{.*#+}} xmm0 = [123456789012345,987654321098765]
; WIN-NEXT:    vmovups %xmm0, (%rcx)
; WIN-NEXT:    retq
  store <2 x i64> <i64 123456789012345, i64 987654321098765>, ptr %dst, align 1
  ret void
}

; Preserve live GPR values across the copy.
define void @gpr_pressure(ptr %src, ptr %dst, ptr %sink, i64 %x) {
; SSE-LABEL: gpr_pressure:
; SSE:       # %bb.0:
; SSE-NEXT:    pushq %r14
; SSE-NEXT:    .cfi_def_cfa_offset 16
; SSE-NEXT:    pushq %rbx
; SSE-NEXT:    .cfi_def_cfa_offset 24
; SSE-NEXT:    .cfi_offset %rbx, -24
; SSE-NEXT:    .cfi_offset %r14, -16
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq 64(%rdi), %r8
; SSE-NEXT:    movq 72(%rdi), %r9
; SSE-NEXT:    movq 80(%rdi), %r10
; SSE-NEXT:    movq 88(%rdi), %r11
; SSE-NEXT:    movq 96(%rdi), %rbx
; SSE-NEXT:    movq 104(%rdi), %r14
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    movq %rcx, (%rsi)
; SSE-NEXT:    movq %r8, (%rdx)
; SSE-NEXT:    movq %r9, 8(%rdx)
; SSE-NEXT:    movq %r10, 16(%rdx)
; SSE-NEXT:    movq %r11, 24(%rdx)
; SSE-NEXT:    movq %rbx, 32(%rdx)
; SSE-NEXT:    movq %r14, 40(%rdx)
; SSE-NEXT:    popq %rbx
; SSE-NEXT:    .cfi_def_cfa_offset 16
; SSE-NEXT:    popq %r14
; SSE-NEXT:    .cfi_def_cfa_offset 8
; SSE-NEXT:    retq
;
; AVX-LABEL: gpr_pressure:
; AVX:       # %bb.0:
; AVX-NEXT:    pushq %r14
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    pushq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 24
; AVX-NEXT:    .cfi_offset %rbx, -24
; AVX-NEXT:    .cfi_offset %r14, -16
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq 64(%rdi), %r8
; AVX-NEXT:    movq 72(%rdi), %r9
; AVX-NEXT:    movq 80(%rdi), %r10
; AVX-NEXT:    movq 88(%rdi), %r11
; AVX-NEXT:    movq 96(%rdi), %rbx
; AVX-NEXT:    movq 104(%rdi), %r14
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq %rcx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    movq %r8, (%rdx)
; AVX-NEXT:    movq %r9, 8(%rdx)
; AVX-NEXT:    movq %r10, 16(%rdx)
; AVX-NEXT:    movq %r11, 24(%rdx)
; AVX-NEXT:    movq %rbx, 32(%rdx)
; AVX-NEXT:    movq %r14, 40(%rdx)
; AVX-NEXT:    popq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    popq %r14
; AVX-NEXT:    .cfi_def_cfa_offset 8
; AVX-NEXT:    retq
;
; WIN-LABEL: gpr_pressure:
; WIN:       # %bb.0:
; WIN-NEXT:    pushq %r14
; WIN-NEXT:    .seh_pushreg %r14
; WIN-NEXT:    pushq %rsi
; WIN-NEXT:    .seh_pushreg %rsi
; WIN-NEXT:    pushq %rdi
; WIN-NEXT:    .seh_pushreg %rdi
; WIN-NEXT:    pushq %rbx
; WIN-NEXT:    .seh_pushreg %rbx
; WIN-NEXT:    .seh_endprologue
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq 64(%rcx), %r10
; WIN-NEXT:    movq 72(%rcx), %r11
; WIN-NEXT:    movq 80(%rcx), %rsi
; WIN-NEXT:    movq 88(%rcx), %rdi
; WIN-NEXT:    movq 96(%rcx), %rbx
; WIN-NEXT:    movq 104(%rcx), %r14
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq %r9, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    movq %r10, (%r8)
; WIN-NEXT:    movq %r11, 8(%r8)
; WIN-NEXT:    movq %rsi, 16(%r8)
; WIN-NEXT:    movq %rdi, 24(%r8)
; WIN-NEXT:    movq %rbx, 32(%r8)
; WIN-NEXT:    movq %r14, 40(%r8)
; WIN-NEXT:    .seh_startepilogue
; WIN-NEXT:    popq %rbx
; WIN-NEXT:    popq %rdi
; WIN-NEXT:    popq %rsi
; WIN-NEXT:    popq %r14
; WIN-NEXT:    .seh_endepilogue
; WIN-NEXT:    retq
; WIN-NEXT:    .seh_endproc
  %p0 = getelementptr i8, ptr %src, i64 64
  %v0 = load i64, ptr %p0, align 8
  %p1 = getelementptr i8, ptr %src, i64 72
  %v1 = load i64, ptr %p1, align 8
  %p2 = getelementptr i8, ptr %src, i64 80
  %v2 = load i64, ptr %p2, align 8
  %p3 = getelementptr i8, ptr %src, i64 88
  %v3 = load i64, ptr %p3, align 8
  %p4 = getelementptr i8, ptr %src, i64 96
  %v4 = load i64, ptr %p4, align 8
  %p5 = getelementptr i8, ptr %src, i64 104
  %v5 = load i64, ptr %p5, align 8
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  %q0 = getelementptr i8, ptr %sink, i64 0
  store volatile i64 %v0, ptr %q0, align 8
  %q1 = getelementptr i8, ptr %sink, i64 8
  store volatile i64 %v1, ptr %q1, align 8
  %q2 = getelementptr i8, ptr %sink, i64 16
  store volatile i64 %v2, ptr %q2, align 8
  %q3 = getelementptr i8, ptr %sink, i64 24
  store volatile i64 %v3, ptr %q3, align 8
  %q4 = getelementptr i8, ptr %sink, i64 32
  store volatile i64 %v4, ptr %q4, align 8
  %q5 = getelementptr i8, ptr %sink, i64 40
  store volatile i64 %v5, ptr %q5, align 8
  ret void
}

; Preserve live SIMD values across the copy.
define void @simd_pressure(ptr %src, ptr %dst, ptr %sink, i64 %x) {
; SSE-LABEL: simd_pressure:
; SSE:       # %bb.0:
; SSE-NEXT:    movups 64(%rdi), %xmm0
; SSE-NEXT:    movups 80(%rdi), %xmm1
; SSE-NEXT:    movups 96(%rdi), %xmm2
; SSE-NEXT:    movups 112(%rdi), %xmm3
; SSE-NEXT:    movups 128(%rdi), %xmm4
; SSE-NEXT:    movq %rcx, (%rdi)
; SSE-NEXT:    movq 8(%rdi), %rax
; SSE-NEXT:    movq %rax, 8(%rsi)
; SSE-NEXT:    movq %rcx, (%rsi)
; SSE-NEXT:    movups %xmm0, (%rdx)
; SSE-NEXT:    movups %xmm1, 16(%rdx)
; SSE-NEXT:    movups %xmm2, 32(%rdx)
; SSE-NEXT:    movups %xmm3, 48(%rdx)
; SSE-NEXT:    movups %xmm4, 64(%rdx)
; SSE-NEXT:    retq
;
; AVX-LABEL: simd_pressure:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovups 64(%rdi), %xmm0
; AVX-NEXT:    vmovups 80(%rdi), %xmm1
; AVX-NEXT:    vmovups 96(%rdi), %xmm2
; AVX-NEXT:    vmovups 112(%rdi), %xmm3
; AVX-NEXT:    vmovups 128(%rdi), %xmm4
; AVX-NEXT:    movq 8(%rdi), %rax
; AVX-NEXT:    movq %rcx, (%rdi)
; AVX-NEXT:    movq %rcx, (%rsi)
; AVX-NEXT:    movq %rax, 8(%rsi)
; AVX-NEXT:    vmovups %xmm0, (%rdx)
; AVX-NEXT:    vmovups %xmm1, 16(%rdx)
; AVX-NEXT:    vmovups %xmm2, 32(%rdx)
; AVX-NEXT:    vmovups %xmm3, 48(%rdx)
; AVX-NEXT:    vmovups %xmm4, 64(%rdx)
; AVX-NEXT:    retq
;
; WIN-LABEL: simd_pressure:
; WIN:       # %bb.0:
; WIN-NEXT:    vmovups 64(%rcx), %xmm0
; WIN-NEXT:    vmovups 80(%rcx), %xmm1
; WIN-NEXT:    vmovups 96(%rcx), %xmm2
; WIN-NEXT:    vmovups 112(%rcx), %xmm3
; WIN-NEXT:    vmovups 128(%rcx), %xmm4
; WIN-NEXT:    movq 8(%rcx), %rax
; WIN-NEXT:    movq %r9, (%rcx)
; WIN-NEXT:    movq %r9, (%rdx)
; WIN-NEXT:    movq %rax, 8(%rdx)
; WIN-NEXT:    vmovups %xmm0, (%r8)
; WIN-NEXT:    vmovups %xmm1, 16(%r8)
; WIN-NEXT:    vmovups %xmm2, 32(%r8)
; WIN-NEXT:    vmovups %xmm3, 48(%r8)
; WIN-NEXT:    vmovups %xmm4, 64(%r8)
; WIN-NEXT:    retq
  %p0 = getelementptr i8, ptr %src, i64 64
  %v0 = load <2 x i64>, ptr %p0, align 8
  %p1 = getelementptr i8, ptr %src, i64 80
  %v1 = load <2 x i64>, ptr %p1, align 8
  %p2 = getelementptr i8, ptr %src, i64 96
  %v2 = load <2 x i64>, ptr %p2, align 8
  %p3 = getelementptr i8, ptr %src, i64 112
  %v3 = load <2 x i64>, ptr %p3, align 8
  %p4 = getelementptr i8, ptr %src, i64 128
  %v4 = load <2 x i64>, ptr %p4, align 8
  store i64 %x, ptr %src, align 8
  call void @llvm.memmove.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  %q0 = getelementptr i8, ptr %sink, i64 0
  store volatile <2 x i64> %v0, ptr %q0, align 8
  %q1 = getelementptr i8, ptr %sink, i64 16
  store volatile <2 x i64> %v1, ptr %q1, align 8
  %q2 = getelementptr i8, ptr %sink, i64 32
  store volatile <2 x i64> %v2, ptr %q2, align 8
  %q3 = getelementptr i8, ptr %sink, i64 48
  store volatile <2 x i64> %v3, ptr %q3, align 8
  %q4 = getelementptr i8, ptr %sink, i64 64
  store volatile <2 x i64> %v4, ptr %q4, align 8
  ret void
}

; Do not replace a non-temporal vector load with an ordinary scalar access.
define void @nontemporal_load(ptr %src, ptr %dst, i64 %x) {
; SSE-LABEL: nontemporal_load:
; SSE:       # %bb.0:
; SSE-NEXT:    movq %rdx, (%rdi)
; SSE-NEXT:    movaps (%rdi), %xmm0
; SSE-NEXT:    movaps %xmm0, (%rsi)
; SSE-NEXT:    retq
;
; AVX-LABEL: nontemporal_load:
; AVX:       # %bb.0:
; AVX-NEXT:    movq %rdx, (%rdi)
; AVX-NEXT:    vmovntdqa (%rdi), %xmm0
; AVX-NEXT:    vmovdqa %xmm0, (%rsi)
; AVX-NEXT:    retq
;
; WIN-LABEL: nontemporal_load:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %r8, (%rcx)
; WIN-NEXT:    vmovntdqa (%rcx), %xmm0
; WIN-NEXT:    vmovdqa %xmm0, (%rdx)
; WIN-NEXT:    retq
  store i64 %x, ptr %src, align 16
  %v = load <2 x i64>, ptr %src, align 16, !nontemporal !0
  store <2 x i64> %v, ptr %dst, align 16
  ret void
}
